/****** File: 000_R1.0_CREATE_EVADO_DIGITAL_TABLES.sql ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

DECLARE @RC int

EXECUTE @RC = [dbo].[usr_DB_Add_Database_Update] 
   0, 'R1.0','EvFormRecords EvCommonFormRecords ', 
   'CREATE EVADO DIGITAL RECORD TABLES.'

GO

PRINT N'START: 000_R1.0_CREATE_EVADO_DIGITAL_TABLES.'; 
GO

/****** Object:  Table [dbo].[EF_FORM_FIELDS]    Script Date: 12/24/2020 10:45:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[EF_FORM_FIELDS](
	[FORM_GUID] [uniqueidentifier] NOT NULL,
	[FORM_FIELD_GUID] [uniqueidentifier] NOT NULL,
	[FORM_FIELD_ID] [nvarchar](20) NOT NULL,
	[FORM_FIELD_TYPE_ID] [varchar](30) NULL,
	[FORM_FIELD_TITLE] [nvarchar](150) NULL,
	[FORM_FIELD_UNIT] [nvarchar](15) NULL,
	[FORM_FIELD_XML_VALIDATION] [ntext] NULL,
	[FORM_FIELD_XML_DESIGN] [ntext] NULL,
	[FORM_FIELD_ORDER] [smallint] NULL,
	[FORM_FIELD_GROUP_ID] [smallint] NULL,
	[FORM_FIELD_STATIC] [bit] NULL,
	[FORM_FIELD_MANDATORY] [bit] NULL,
	[FORM_FIELD_HIDDEN] [bit] NULL,
	[FORM_FIELD_INITIAL_VERSION] [smallint] NULL,
	[FORM_FIELD_DELETED] [bit] NULL,
 CONSTRAINT [PK_FORM_FIELD] PRIMARY KEY CLUSTERED 
(
	[FORM_FIELD_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[EF_FORM_INDEX_FIELDS]    Script Date: 12/24/2020 10:45:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[EF_FORM_INDEX_FIELDS](
	[FORM_GUID] [uniqueidentifier] NOT NULL,
	[FORM_FIELD_GUID] [uniqueidentifier] NOT NULL,
	[FORM_FIELD_ID] [nvarchar](20) NOT NULL,
	[FORM_FIELD_TYPE_ID] [varchar](30) NULL,
	[FORM_FIELD_TITLE] [nvarchar](150) NULL,
	[FORM_FIELD_UNIT] [nvarchar](15) NULL,
	[FORM_FIELD_XML_VALIDATION] [ntext] NULL,
	[FORM_FIELD_XML_DESIGN] [ntext] NULL,
	[FORM_FIELD_ORDER] [smallint] NULL,
	[FORM_FIELD_GROUP_ID] [smallint] NULL,
	[FORM_FIELD_STATIC] [bit] NULL,
	[FORM_FIELD_MANDATORY] [bit] NULL,
	[FORM_FIELD_HIDDEN] [bit] NULL,
	[FORM_FIELD_INITIAL_VERSION] [smallint] NULL,
	[FORM_FIELD_DELETED] [bit] NULL,
 CONSTRAINT [PK_FORM_INDEXES_FIELD] PRIMARY KEY CLUSTERED 
(
	[FORM_FIELD_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


/****** Object:  Table [dbo].[EF_FORM_INDEX_RECORD_VALUES]    Script Date: 12/24/2020 10:45:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EF_FORM_INDEX_RECORD_VALUES](
	[FORM_RECORD_GUID] [uniqueidentifier] NULL,
	[FORM_FIELD_GUID] [uniqueidentifier] NULL,
	[FORM_RECORD_VALUE_GUID] [uniqueidentifier] NOT NULL,
	[FORM_RECORD_VALUE_COLUMN] [smallint] NULL,
	[FORM_RECORD_VALUE_ROW] [smallint] NULL,
	[FORM_RECORD_VALUE_STRING] [nvarchar](100) NULL,
	[FORM_RECORD_VALUE_NUMERIC] [float] NULL,
	[FORM_RECORD_VALUE_DATE] [datetime] NULL,
	[FORM_RECORD_VALUE_TEXT] [ntext] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

USE [EVADO_FORMS]
GO

/****** Object:  Table [dbo].[EF_FORM_INDEX_RECORDS]    Script Date: 12/24/2020 10:45:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EF_FORM_INDEX_RECORDS](
	[FORM_RECORD_GUID] [uniqueidentifier] NOT NULL,
	[FORM_GUID] [uniqueidentifier] NULL,
	[RECORD_FILE_ID] [nvarchar](10) NULL,
	[RECORD_FILTER_0] [nvarchar](100) NULL,
	[RECORD_FILTER_1] [nvarchar](100) NULL,
	[RECORD_FILTER_2] [nvarchar](100) NULL,
	[RECORD_FILTER_3] [nvarchar](100) NULL,
	[RECORD_FILTER_4] [nvarchar](100) NULL,
	[FORM_RECORD_STATE] [varchar](30) NOT NULL,
	[FORM_RECORD_PREFIX] [nvarchar](5) NULL,
	[FORM_RECORD_ID] [nvarchar](10) NULL,
	[FORM_RECORD_DATE] [datetime] NULL,
	[FORM_RECORD_COMMENTS] [ntext] NULL,
	[FORM_RECORD_SERIAL_ID] [int] NULL,
	[FORM_RECORD_BOOKED_OUT_USER_ID] [nvarchar](100) NULL,
	[FORM_RECORD_BOOKED_OUT] [nvarchar](100) NULL,
	[FORM_RECORD_XML_CONTENT] [nvarchar](max) NULL,
	[FORM_RECORD_IS_MANDATORY] [bit] NULL,
	[FORM_RECORD_SOURCE_ID] [varchar](20) NULL,
	[FORM_RECORD_UPDATED_BY_USER_ID] [nvarchar](100) NULL,
	[FORM_RECORD_UPDATED_BY] [nvarchar](100) NULL,
	[FORM_RECORD_UPDATED_DATE] [datetime] NULL,
	[FORM_RECORD_RECORD_DELETED] [bit] NULL,
 CONSTRAINT [PK_FORM_INDEXES_RECORDS] PRIMARY KEY CLUSTERED 
(
	[FORM_RECORD_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[EF_FORM_INDEXES]    Script Date: 12/24/2020 10:45:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[EF_FORM_INDEXES](
	[FORM_GUID] [uniqueidentifier] NOT NULL,
	[FORM_ID] [nvarchar](20) NULL,
	[FORM_STATE] [varchar](50) NULL,
	[FORM_OWNER] [uniqueidentifier] NULL,
	[FORM_CATEGORY] [nvarchar](100) NULL,
	[FORM_TITLE] [nvarchar](100) NOT NULL,
	[FORM_TYPE_ID] [varchar](30) NOT NULL,
	[FORM_VERSION] [float] NULL,
	[FORM_XML_VALIDATION_RULES] [nvarchar](max) NULL,
	[FORM_XML_DESIGN] [nvarchar](max) NULL,
	[FORM_UPDATED_BY_USER_ID] [nvarchar](100) NULL,
	[FORM_UPDATED_BY] [nvarchar](100) NULL,
	[FORM_UPDATED_DATE] [datetime] NULL,
	[FORM_DELETED] [bit] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[EF_FORM_RECORD_VALUES]    Script Date: 12/24/2020 10:45:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EF_FORM_RECORD_VALUES](
	[FORM_RECORD_GUID] [uniqueidentifier] NULL,
	[FORM_FIELD_GUID] [uniqueidentifier] NULL,
	[FORM_RECORD_VALUE_GUID] [uniqueidentifier] NOT NULL,
	[FORM_RECORD_VALUE_COLUMN] [smallint] NULL,
	[FORM_RECORD_VALUE_ROW] [smallint] NULL,
	[FORM_RECORD_VALUE_STRING] [nvarchar](100) NULL,
	[FORM_RECORD_VALUE_NUMERIC] [float] NULL,
	[FORM_RECORD_VALUE_DATE] [datetime] NULL,
	[FORM_RECORD_VALUE_TEXT] [ntext] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

/****** Object:  Table [dbo].[EF_FORM_RECORDS]    Script Date: 12/24/2020 10:45:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[EF_FORM_RECORDS](
	[FORM_RECORD_GUID] [uniqueidentifier] NOT NULL,
	[FORM_GUID] [uniqueidentifier] NULL,
	[FORM_RECORD_STATE] [varchar](30) NOT NULL,
	[RECORD_FILE_ID] [nvarchar](10) NULL,
	[RECORD_INDEX_0] [nvarchar](20) NULL,
	[RECORD_INDEX_1] [nvarchar](20) NULL,
	[RECORD_INDEX_2] [nvarchar](20) NULL,
	[RECORD_INDEX_3] [nvarchar](20) NULL,
	[RECORD_INDEX_4] [nvarchar](20) NULL,
	[RECORD_INDEX_5] [nvarchar](20) NULL,
	[RECORD_INDEX_6] [nvarchar](20) NULL,
	[RECORD_INDEX_7] [nvarchar](20) NULL,
	[RECORD_INDEX_8] [nvarchar](20) NULL,
	[RECORD_INDEX_9] [nvarchar](20) NULL,
	[RECORD_FILTER_0] [nvarchar](100) NULL,
	[RECORD_FILTER_1] [nvarchar](100) NULL,
	[RECORD_FILTER_2] [nvarchar](100) NULL,
	[RECORD_FILTER_3] [nvarchar](100) NULL,
	[RECORD_FILTER_4] [nvarchar](100) NULL,
	[SOP_STEP_ID] [nvarchar](20) NULL,
	[FORM_RECORD_ID] [nvarchar](20) NULL,
	[FORM_RECORD_DATE] [datetime] NULL,
	[FORM_RECORD_COMMENTS] [ntext] NULL,
	[FORM_RECORD_SERIAL_ID] [int] NULL,
	[FORM_RECORD_BOOKED_OUT_USER_ID] [nvarchar](100) NULL,
	[FORM_RECORD_BOOKED_OUT] [nvarchar](100) NULL,
	[FORM_RECORD_XML_CONTENT] [nvarchar](max) NULL,
	[FORM_RECORD_IS_MANDATORY] [bit] NULL,
	[FORM_RECORD_SOURCE_ID] [varchar](20) NULL,
	[FORM_RECORD_UPDATED_BY_USER_ID] [nvarchar](100) NULL,
	[FORM_RECORD_UPDATED_BY] [nvarchar](100) NULL,
	[FORM_RECORD_UPDATED_DATE] [datetime] NULL,
	[FORM_RECORD_RECORD_DELETED] [bit] NULL,
 CONSTRAINT [PK_FORM_RECORDS] PRIMARY KEY CLUSTERED 
(
	[FORM_RECORD_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


/****** Object:  Table [dbo].[EF_FORMS]    Script Date: 12/24/2020 10:45:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[EF_FORMS](
	[FORM_GUID] [uniqueidentifier] NOT NULL,
	[FORM_ID] [nvarchar](20) NULL,
	[FORM_STATE] [varchar](50) NULL,
	[FORM_OWNER] [uniqueidentifier] NULL,
	[FORM_CATEGORY] [nvarchar](100) NULL,
	[FORM_TITLE] [nvarchar](100) NOT NULL,
	[FORM_TYPE_ID] [varchar](30) NOT NULL,
	[FORM_VERSION] [float] NULL,
	[FORM_XML_VALIDATION_RULES] [nvarchar](max) NULL,
	[FORM_XML_DESIGN] [nvarchar](max) NULL,
	[FORM_UPDATED_BY_USER_ID] [nvarchar](100) NULL,
	[FORM_UPDATED_BY] [nvarchar](100) NULL,
	[FORM_UPDATED_DATE] [datetime] NULL,
	[FORM_DELETED] [bit] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[EF_FORM_FIELDS] ADD  CONSTRAINT [DF_FORM_FIELD_GUID]  DEFAULT (newid()) FOR [FORM_FIELD_GUID]
GO

ALTER TABLE [dbo].[EF_FORM_FIELDS] ADD  CONSTRAINT [DF_FORM_FIELD_ORDER]  DEFAULT ((0)) FOR [FORM_FIELD_ORDER]
GO

ALTER TABLE [dbo].[EF_FORM_FIELDS] ADD  CONSTRAINT [DF_FORM_FIELD_DELETED]  DEFAULT ((0)) FOR [FORM_FIELD_DELETED]
GO

ALTER TABLE [dbo].[EF_FORM_INDEX_FIELDS] ADD  CONSTRAINT [DF_FORM_INDEX_FIELD_GUID]  DEFAULT (newid()) FOR [FORM_FIELD_GUID]
GO

ALTER TABLE [dbo].[EF_FORM_INDEX_FIELDS] ADD  CONSTRAINT [DF_FORM_INDEX_FIELD_ORDER]  DEFAULT ((0)) FOR [FORM_FIELD_ORDER]
GO

ALTER TABLE [dbo].[EF_FORM_INDEX_FIELDS] ADD  CONSTRAINT [DF_FORM_INDEX_FIELD_DELETED]  DEFAULT ((0)) FOR [FORM_FIELD_DELETED]
GO

ALTER TABLE [dbo].[EF_FORM_INDEX_RECORD_VALUES] ADD  CONSTRAINT [DF_FORM_INDEX_RECORD_VALUE_GUID]  DEFAULT (newid()) FOR [FORM_RECORD_VALUE_GUID]
GO

ALTER TABLE [dbo].[EF_FORM_INDEX_RECORD_VALUES] ADD  CONSTRAINT [DF_FORM_INDEX_RECORD_VALUE_COLUMN]  DEFAULT ((0)) FOR [FORM_RECORD_VALUE_COLUMN]
GO

ALTER TABLE [dbo].[EF_FORM_INDEX_RECORD_VALUES] ADD  CONSTRAINT [DF_FORM_INDEX_RECORD_VALUE_ROW]  DEFAULT ((0)) FOR [FORM_RECORD_VALUE_ROW]
GO

ALTER TABLE [dbo].[EF_FORM_INDEX_RECORDS] ADD  CONSTRAINT [DF_FORM_INDEX_RECORD_GUID]  DEFAULT (newid()) FOR [FORM_RECORD_GUID]
GO

ALTER TABLE [dbo].[EF_FORM_INDEX_RECORDS] ADD  CONSTRAINT [DF_FORM_INDEX_RECORD_STATE]  DEFAULT ('Draft_Record') FOR [FORM_RECORD_STATE]
GO

ALTER TABLE [dbo].[EF_FORM_INDEX_RECORDS] ADD  CONSTRAINT [DF_FORM_INDEX_RECORDS_SERIAL_ID]  DEFAULT ((0)) FOR [FORM_RECORD_SERIAL_ID]
GO

ALTER TABLE [dbo].[EF_FORM_INDEX_RECORDS] ADD  CONSTRAINT [DF_FORM_INDEX_RECORD_IS_MANDATORY]  DEFAULT ((0)) FOR [FORM_RECORD_IS_MANDATORY]
GO

ALTER TABLE [dbo].[EF_FORM_INDEXES] ADD  CONSTRAINT [DF_FORM_INDEX_GUID]  DEFAULT (newid()) FOR [FORM_GUID]
GO

ALTER TABLE [dbo].[EF_FORM_INDEXES] ADD  CONSTRAINT [DF_FORM_INDEX_VERSION]  DEFAULT ((0.0)) FOR [FORM_VERSION]
GO

ALTER TABLE [dbo].[EF_FORM_INDEXES] ADD  CONSTRAINT [DF_FORM_INDEX_DELETED]  DEFAULT ((0)) FOR [FORM_DELETED]
GO

ALTER TABLE [dbo].[EF_FORM_RECORD_VALUES] ADD  CONSTRAINT [DF_FORM_RECORD_VALUE_GUID]  DEFAULT (newid()) FOR [FORM_RECORD_VALUE_GUID]
GO

ALTER TABLE [dbo].[EF_FORM_RECORD_VALUES] ADD  CONSTRAINT [DF_FORM_RECORD_VALUE_COLUMN]  DEFAULT ((0)) FOR [FORM_RECORD_VALUE_COLUMN]
GO

ALTER TABLE [dbo].[EF_FORM_RECORD_VALUES] ADD  CONSTRAINT [DF_FORM_RECORD_VALUE_ROW]  DEFAULT ((0)) FOR [FORM_RECORD_VALUE_ROW]
GO

ALTER TABLE [dbo].[EF_FORM_RECORDS] ADD  CONSTRAINT [DF_FORM_RECORD_GUID]  DEFAULT (newid()) FOR [FORM_RECORD_GUID]
GO

ALTER TABLE [dbo].[EF_FORM_RECORDS] ADD  CONSTRAINT [DF_FORM_RECORD_STATE]  DEFAULT ('Draft_Record') FOR [FORM_RECORD_STATE]
GO

ALTER TABLE [dbo].[EF_FORM_RECORDS] ADD  CONSTRAINT [DF_FORM_RECORDS_SERIAL_ID]  DEFAULT ((0)) FOR [FORM_RECORD_SERIAL_ID]
GO

ALTER TABLE [dbo].[EF_FORM_RECORDS] ADD  CONSTRAINT [DF_FORM_RECORD_IS_MANDATORY]  DEFAULT ((0)) FOR [FORM_RECORD_IS_MANDATORY]
GO

ALTER TABLE [dbo].[EF_FORMS] ADD  CONSTRAINT [DF_FORM_GUID]  DEFAULT (newid()) FOR [FORM_GUID]
GO

ALTER TABLE [dbo].[EF_FORMS] ADD  CONSTRAINT [DF_FORM_VERSION]  DEFAULT ((0.0)) FOR [FORM_VERSION]
GO

ALTER TABLE [dbo].[EF_FORMS] ADD  CONSTRAINT [DF_FORM_DELETED]  DEFAULT ((0)) FOR [FORM_DELETED]
GO


PRINT N'FINISH: 000_R1.0_CREATE_EVADO_DIGITAL_TABLES.'; 
GO
