/****** File: 003_R1.0_ED_RECORD_LAYOUTS_CREATE_STORED_PROCEDURES.sql ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

DECLARE @RC int

EXECUTE @RC = dbo.usr_DB_Add_Database_Update 
   003, 'R1.0','ED_RECORD_LAYOUTS', 
   'CREATE STORED PROCEDURES.'

GO

PRINT N'START: 003_R1.0_ED_RECORD_LAYOUTS_CREATE_STORED_PROCEDURES.'; 
GO

/****** Object:  StoredProcedure dbo.USR_RECORD_LAYOUT_ADD    Script Date: 01/04/2021 10:32:51 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.USR_RECORD_LAYOUT_ADD') AND type in (N'P', N'PC'))
DROP PROCEDURE dbo.USR_RECORD_LAYOUT_ADD
GO

/****** Object:  StoredProcedure dbo.USR_RECORD_LAYOUT_COPY    Script Date: 01/04/2021 10:32:51 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.USR_RECORD_LAYOUT_COPY') AND type in (N'P', N'PC'))
DROP PROCEDURE dbo.USR_RECORD_LAYOUT_COPY
GO

/****** Object:  StoredProcedure dbo.USR_RECORD_LAYOUT_DELETE    Script Date: 01/04/2021 10:32:51 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.USR_RECORD_LAYOUT_DELETE') AND type in (N'P', N'PC'))
DROP PROCEDURE dbo.USR_RECORD_LAYOUT_DELETE
GO

/****** Object:  StoredProcedure dbo.USR_RECORD_LAYOUT_UPDATE    Script Date: 01/04/2021 10:32:51 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.USR_RECORD_LAYOUT_UPDATE') AND type in (N'P', N'PC'))
DROP PROCEDURE dbo.USR_RECORD_LAYOUT_UPDATE
GO

/****** Object:  StoredProcedure dbo.USR_RECORD_LAYOUT_WITHDRAWN    Script Date: 01/04/2021 10:32:51 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.USR_RECORD_LAYOUT_WITHDRAWN') AND type in (N'P', N'PC'))
DROP PROCEDURE dbo.USR_RECORD_LAYOUT_WITHDRAWN
GO

/****** Object:  View dbo.EvForm_View    Script Date: 01/05/2021 10:02:06 ******/
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'dbo.EvForm_View'))
DROP VIEW dbo.EvForm_View
GO

/****** Object:  View dbo.EvForm_View    Script Date: 01/05/2021 10:02:06 ******/
CREATE VIEW dbo.EvForm_View
AS
SELECT  
 CU_GUID,    
  TC_Guid, 
  TrialId, 
  FormId, 
  TC_Version, 
  TC_State, 
  TC_Title, 
  TC_Reference, 
  TC_Authors, 
  TC_ReviewedBy, 
  TC_ReviewedDate, 
  TC_ApprovedBy, 
  TC_ApprovalDate, 
  TC_TypeId, 
  TC_UpdatedBy, 
  TC_UpdateDate, 
  TC_Superseded, 
  TC_Instructions, 
  TC_ReviewedByUserId, 
  TC_ApprovedByUserID, 
  TC_UpdatedByUserId, 
  TC_XmlValidationRules, 
  TC_XmlData,
  TC_CDASH_METADATA,
  TC_TEMPLATE_NAME,
  TC_JAVA_VALIDATION_SCRIPT,
  TC_FORM_CATEGORY,
  TC_HAS_CS_SCRIPT,
  TC_HAS_SECTION_NAVIGATION,
  TC_HIDDEN_FIELDS,
  TC_REGULATORY_TEMPLATE,
  TC_HIDE_ANNOTATION_DURING_EDITING,
  TC_TRIAL_SITES,
  TC_DESCRIPTION,
  TC_UPDATE_REASON
     
FROM         dbo.EvForms
WHERE     (TC_Superseded = 0)


GO

/****** Object:  StoredProcedure dbo.USR_RECORD_LAYOUT_ADD    Script Date: 01/04/2021 10:32:51 ******/
CREATE PROCEDURE dbo.USR_RECORD_LAYOUT_ADD
 @CUSTOMER_GUID UniqueIdentifier,
 @GUID UniqueIdentifier,
 @APPLICATION_ID NVarChar (10),
 @LAYOUT_ID NVarChar(20),
 @STATE  NVarChar(20),
 @TITLE NVarChar(80),
 @HTTP_REFERENCE NVarChar(250),
 @INSTRUCTIONS NText,
 @DESCRIPTION NText,   
 @UPDATE_REASON  NVarChar(50),
 @RECORD_CATEGORY NVarChar(100),
 @TYPE_ID VarChar(25),
 @VERSION Float,
 @JAVA_SCRIPT NText,   
 @HAS_CS_SCRIPT Bit,
 @LANGUAGE VarChar(5),
 @CDASH_METADATA NVarChar(250),
 @UPDATED_BY_USER_ID NVarChar(100),
 @UPDATED_BY NVarChar(30),
 @UPDATED_DATE DateTime
AS

Insert Into ED_RECORD_LAYOUTS 
  (CU_GUID
  , EDRL_GUID 
  , APPLICATION_ID 
  , LAYOUT_ID 
  , EDRL_STATE 
  , EDRL_TITLE 
  , EDRL_HTTP_REFERENCE 
  , EDRL_INSTRUCTIONS 
  , EDRL_DESCRIPTION 
  , EDRL_UPDATE_REASON 
  , EDRL_RECORD_CATEGORY 
  , EDRL_TYPE_ID 
  , EDRL_VERSION 
  , EDRL_JAVA_SCRIPT 
  , EDRL_HAS_CS_SCRIPT 
  , EDRL_LANGUAGE 
  , EDRL_CDASH_METADATA 
  , EDRL_UPDATED_BY_USER_ID 
  , EDRL_UPDATED_BY 
  , EDRL_UPDATED_DATE 
  , EDRL_DELETED  ) 
values 
 ( @CUSTOMER_GUID,
   @GUID,
   @APPLICATION_ID,
   @LAYOUT_ID,
   @STATE,
   @TITLE,
   @HTTP_REFERENCE,
   @INSTRUCTIONS,
   @DESCRIPTION,
   @UPDATE_REASON,
   @RECORD_CATEGORY,
   @TYPE_ID,
   @VERSION,
   @JAVA_SCRIPT,
   @HAS_CS_SCRIPT,
   @LANGUAGE,
   @CDASH_METADATA,
   @UPDATED_BY_USER_Id ,
   @UPDATED_BY,
   @UPDATED_DATE,0  );

GO

/****** Object:  StoredProcedure dbo.USR_RECORD_LAYOUT_COPY    Script Date: 01/04/2021 10:32:51 ******/

CREATE PROCEDURE dbo.USR_RECORD_LAYOUT_COPY
 @GUID UniqueIdentifier,
 @VERSION Float,
 @Copy bit,
 @UPDATED_BY_USER_ID NVarChar(100),
 @UPDATED_BY NVarChar(30),
 @UPDATED_DATE DateTime
AS

DECLARE @NewGuid uniqueidentifier
DECLARE @LAYOUT_id varchar(20)
DECLARE @Title varchar(100)
DECLARE @CopyId varchar(4)

SET @NewGuid =  newid()

/***** Revise the form  ****/
SELECT @LAYOUT_ID = @LAYOUT_ID,  @Title = EDRL_TITLE 
FROM ED_RECORD_LAYOUTS 
WHERE (EDRL_GUID = @GUID);

IF ( @Copy = 1 )
BEGIN

SET @Version ='0.00'
SET @Title = SUBSTRING ( '(COPY) ' + @Title, 1, 100 )
SET @LAYOUT_ID = SUBSTRING ( 'CPY_' + @LAYOUT_ID , 1 , 20 ) 

END

/** COPY THE FORM CVALUES IN TO THE FORM OBJECT.**/
Insert Into ED_RECORD_LAYOUTS 
  ( CU_GUID
  , EDRL_GUID 
  , APPLICATION_ID 
  , LAYOUT_ID 
  , EDRL_STATE 
  , EDRL_TITLE 
  , EDRL_HTTP_REFERENCE 
  , EDRL_INSTRUCTIONS 
  , EDRL_DESCRIPTION 
  , EDRL_UPDATE_REASON 
  , EDRL_RECORD_CATEGORY 
  , EDRL_TYPE_ID 
  , EDRL_VERSION 
  , EDRL_JAVA_SCRIPT 
  , EDRL_HAS_CS_SCRIPT 
  , EDRL_LANGUAGE 
  , EDRL_CDASH_METADATA 
  , EDRL_UPDATED_BY_USER_ID 
  , EDRL_UPDATED_BY 
  , EDRL_UPDATED_DATE 
  , EDRL_DELETED  ) 
SELECT 
    CU_GUID
  , @NewGuid
  , APPLICATION_ID 
  , @LAYOUT_ID 
  , EDRL_STATE 
  , @Title 
  , EDRL_HTTP_REFERENCE 
  , EDRL_INSTRUCTIONS 
  , EDRL_DESCRIPTION 
  , EDRL_UPDATE_REASON 
  , EDRL_RECORD_CATEGORY 
  , EDRL_TYPE_ID 
  , EDRL_VERSION 
  , EDRL_JAVA_SCRIPT 
  , EDRL_HAS_CS_SCRIPT 
  , EDRL_LANGUAGE 
  , EDRL_CDASH_METADATA 
  , EDRL_UPDATED_BY_USER_ID 
  , EDRL_UPDATED_BY 
  , EDRL_UPDATED_DATE 
  , EDRL_DELETED 
FROM ED_RECORD_LAYOUTS 
WHERE (EDRL_GUID = @GUID);


/** COPY THE FORM SECTION IN TO THE FORM OBJECT.**/
INSERT INTO ED_RECORD_LAYOUT_SECTIONS 
 ( EDRLS_GUID 
  ,EDRL_GUID 
  ,EDRLS_NUMBER 
  ,EDRLS_ORDER 
  ,EDRLS_NAME 
  ,EDRLS_INSTRUCTIONS 
  ,EDRLS_FIELD_NAME 
  ,EDRLS_FIELD_VALUE 
  ,EDRLS_ON_MATCH_VISIBLE 
  ,EDRLS_VISIBLE 
  ,EDRLS_DEFAULT_DISPLAY_ROLES 
  ,EDRLS_DEFAULT_EDIT_ROLES ) 
SELECT 
  newid()
  ,@NewGuid
  ,EDRLS_NUMBER 
  ,EDRLS_ORDER 
  ,EDRLS_NAME 
  ,EDRLS_INSTRUCTIONS 
  ,EDRLS_FIELD_NAME 
  ,EDRLS_FIELD_VALUE 
  ,EDRLS_ON_MATCH_VISIBLE 
  ,EDRLS_VISIBLE 
  ,EDRLS_DEFAULT_DISPLAY_ROLES 
  ,EDRLS_DEFAULT_EDIT_ROLES
FROM ED_RECORD_LAYOUT_SECTIONS 
WHERE (EDRL_GUID = @GUID);

/** COPY THE FORM FIELDS INTO THE NEW FORM OBJECT.**/
INSERT INTO ED_ENTITY_LAYOUT_FIELDS 
 ( EDEL_GUID 
  , EDELF_GUID 
  , LAYOUT_ID 
  , FIELD_ID 
  , EDELF_TYPE_ID 
  , EDELF_ORDER 
  , EDELF_TITLE 
  , EDELF_INSTRUCTIONS 
  , EDELF_HTTP_REFERENCE 
  , EDELF_SECTION_ID 
  , EDELF_OPTIONS 
  , EDELF_SUMMARY_FIELD 
  , EDELF_MANDATORY 
  , EDELF_AI_DATA_POINT 
  , EDELF_HIDDEN 
  , EDELF_DEFAULT_VALUE 
  , EDELF_UNIT 
  , EDELF_UNIT_SCALING 
  , EDELF_VALIDATION_LOWER_LIMIT 
  , EDELF_VALIDATION_UPPER_LIMIT 
  , EDELF_ALERT_LOWER_LIMIT 
  , EDELF_ALERT_UPPER_LIMIT 
  , EDELF_NORMAL_LOWER_LIMIT 
  , EDELF_NORMAL_UPPER_LIMIT 
  , EDELF_ANALOGUE_SCALE 
  , EDELF_ANALOGUE_LEGEND_START 
  , EDELF_ANALOGUE_LEGEND_FINISH 
  , EDELF_JAVA_SCRIPT 
  , EDELF_TABLE 
  , EDELF_INITIAL_OPTION_LIST 
  , EDELF_INITIAL_VERSION 
  , EDELF_DELETED  ) 
SELECT 
   @NewGuid
  , EDELF_GUID
  , LAYOUT_ID 
  , FIELD_ID 
  , EDELF_TYPE_ID 
  , EDELF_ORDER 
  , EDELF_TITLE 
  , EDELF_INSTRUCTIONS 
  , EDELF_HTTP_REFERENCE 
  , EDELF_SECTION_ID 
  , EDELF_OPTIONS 
  , EDELF_SUMMARY_FIELD 
  , EDELF_MANDATORY 
  , EDELF_AI_DATA_POINT 
  , EDELF_HIDDEN 
  , EDELF_DEFAULT_VALUE 
  , EDELF_UNIT 
  , EDELF_UNIT_SCALING 
  , EDELF_VALIDATION_LOWER_LIMIT 
  , EDELF_VALIDATION_UPPER_LIMIT 
  , EDELF_ALERT_LOWER_LIMIT 
  , EDELF_ALERT_UPPER_LIMIT 
  , EDELF_NORMAL_LOWER_LIMIT 
  , EDELF_NORMAL_UPPER_LIMIT 
  , EDELF_ANALOGUE_SCALE 
  , EDELF_ANALOGUE_LEGEND_START 
  , EDELF_ANALOGUE_LEGEND_FINISH 
  , EDELF_JAVA_SCRIPT 
  , EDELF_TABLE 
  , EDELF_INITIAL_OPTION_LIST 
  , EDELF_INITIAL_VERSION 
  ,0
  FROM  EVADO_DIGITAL . dbo . ED_ENTITY_LAYOUT_FIELDS 
WHERE (EDEL_GUID = @GUID) and (EDELF_DELETED = 0);

GO

/****** Object:  StoredProcedure dbo.USR_RECORD_LAYOUT_DELETE    Script Date: 01/04/2021 10:32:51 ******/

CREATE   PROCEDURE dbo.USR_RECORD_LAYOUT_DELETE 
 @GUID UniqueIdentifier ,
 @UPDATED_BY_USER_ID NVarChar (100),
 @UPDATED_BY  NVarChar(30),
 @UPDATED_DATE DateTime
AS

UPDATE ED_RECORD_LAYOUTS 
SET 
  EDRL_UPDATED_BY_USER_ID = @UPDATED_BY_USER_ID,  
  EDRL_UPDATED_BY = @UPDATED_BY,  
  EDRL_UPDATED_DATE = @UPDATED_DATE, 
  EDRL_DELETED = -1 
WHERE 	EDRL_DELETED = 0 
	AND EDRL_GUID = @GUID ;

GO

/****** Object:  StoredProcedure dbo.USR_RECORD_LAYOUT_UPDATE    Script Date: 01/04/2021 10:32:51 ******/

CREATE PROCEDURE dbo.USR_RECORD_LAYOUT_UPDATE
 @CUSTOMER_GUID UniqueIdentifier,
 @GUID UniqueIdentifier,
 @APPLICATION_ID NVarChar (10),
 @LAYOUT_ID NVarChar(20),
 @STATE  NVarChar(20),
 @TITLE NVarChar(80),
 @HTTP_REFERENCE NVarChar(250),
 @INSTRUCTIONS NText,
 @DESCRIPTION NText,   
 @UPDATE_REASON  NVarChar(50),
 @RECORD_CATEGORY NVarChar(100),
 @TYPE_ID VarChar(25),
 @VERSION Float,
 @JAVA_SCRIPT NText,   
 @HAS_CS_SCRIPT Bit,
 @LANGUAGE VarChar(5),
 @CDASH_METADATA NVarChar(250),
 @UPDATED_BY_USER_ID NVarChar(100),
 @UPDATED_BY NVarChar(30),
 @UPDATED_DATE DateTime
AS
UPDATE ED_RECORD_LAYOUTS 
SET 
  APPLICATION_ID = @APPLICATION_ID,
  LAYOUT_ID = @LAYOUT_ID ,
  EDRL_STATE = @STATE  ,
  EDRL_TITLE = @TITLE ,
  EDRL_HTTP_REFERENCE = @HTTP_REFERENCE ,
  EDRL_INSTRUCTIONS = @INSTRUCTIONS ,
  EDRL_DESCRIPTION = @DESCRIPTION ,
  EDRL_UPDATE_REASON = @UPDATE_REASON  ,
  EDRL_RECORD_CATEGORY = @RECORD_CATEGORY  ,
  EDRL_TYPE_ID = @TYPE_ID ,
  EDRL_VERSION = @VERSION,
  EDRL_JAVA_SCRIPT = @JAVA_SCRIPT, 
  EDRL_HAS_CS_SCRIPT = @HAS_CS_SCRIPT,
  EDRL_LANGUAGE = @LANGUAGE,
  EDRL_CDASH_METADATA = @CDASH_METADATA,
  EDRL_UPDATED_BY_USER_ID = @UPDATED_BY_USER_ID,
  EDRL_UPDATED_BY = @UPDATED_BY,
  EDRL_UPDATED_DATE =@UPDATED_DATE
WHERE (EDRL_GUID = @GUID) ;


GO

/****** Object:  StoredProcedure dbo.USR_RECORD_LAYOUT_UPDATE    Script Date: 01/04/2021 10:32:52 ******/

CREATE PROCEDURE dbo.USR_RECORD_LAYOUT_WITHDRAWN
 @APPLICATION_ID NVarChar (10),
 @LAYOUT_ID NVarChar(20),
 @UPDATED_BY_USER_ID NVarChar (100),
 @UPDATED_BY  NVarChar(30),
 @UPDATED_DATE DateTime
AS
UPDATE ED_RECORD_LAYOUTS 
SET 
  EDRL_STATE = 'Withdrawn', 
  EDRL_UPDATED_BY_USER_ID = @UPDATED_BY_USER_ID,
  EDRL_UPDATED_BY = @UPDATED_BY,
  EDRL_UPDATED_DATE =@UPDATED_DATE
WHERE (APPLICATION_ID = @APPLICATION_ID) 
  AND (LAYOUT_ID = @LAYOUT_ID)
  AND (EDRL_STATE = 'Form_Issued' ) ;



GO




PRINT N'FINISH: 003_R1.0_ED_RECORD_LAYOUTS_CREATE_STORED_PROCEDURES.'; 
GO
