/****** File: 005_R1.0_ED_RECORDS_CREATE_STORED_PROCEDURES.sql ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

DECLARE @RC int

EXECUTE @RC = dbo.usr_DB_Add_Database_Update 
   004, 'R1.0','ED_RECORDS', 
   'CREATE STORED PROCEDURES.'
GO

PRINT N'START: 005_R1.0_ED_RECORDs_CREATE_STORED_PROCEDURES.'; 
GO

/****** Object:  StoredProcedure [dbo].[USR_RECORD_CREATE]    Script Date: 01/07/2021 11:18:08 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USR_RECORD_CREATE]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[USR_RECORD_CREATE]
GO

/****** Object:  StoredProcedure [dbo].[USR_RECORD_DELETE]    Script Date: 01/07/2021 11:18:08 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USR_RECORD_DELETE]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[USR_RECORD_DELETE]
GO

/****** Object:  StoredProcedure [dbo].[USR_RECORD_LOCK]    Script Date: 01/07/2021 11:20:00 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USR_RECORD_LOCK]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[USR_RECORD_LOCK]
GO

/****** Object:  StoredProcedure [dbo].[USR_RECORD_UNLOCK]    Script Date: 01/07/2021 11:20:00 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USR_RECORD_UNLOCK]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[USR_RECORD_UNLOCK]
GO

/****** Object:  StoredProcedure [dbo].[USR_RECORD_UPDATE]    Script Date: 01/07/2021 11:20:00 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USR_RECORD_UPDATE]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[USR_RECORD_UPDATE]
GO

/****** Object:  View [dbo].[ED_RECORD_VIEW]    Script Date: 01/07/2021 12:35:38 ******/
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ED_RECORD_VIEW]'))
DROP VIEW [dbo].[ED_RECORD_VIEW]
GO


/****** Object:  View [dbo].[ED_RECORD_FILTER_VIEW]    Script Date: 01/08/2021 10:58:14 ******/
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ED_RECORD_FILTER_VIEW]'))
DROP VIEW [dbo].[ED_RECORD_FILTER_VIEW]
GO

/****** Object:  View [dbo].[ED_RECORD_VIEW]    Script Date: 01/07/2021 12:35:38 ******/

CREATE VIEW [dbo].[ED_RECORD_VIEW]
AS
SELECT
  dbo.ED_RECORD_LAYOUTS.CU_GUID, 
  dbo.ED_RECORDS.EDR_GUID, 
  dbo.ED_RECORD_LAYOUTS.EDRL_GUID, 
  dbo.ED_RECORD_LAYOUTS.APPLICATION_ID, 
  dbo.ED_RECORD_LAYOUTS.LAYOUT_ID, 
  dbo.ED_RECORD_LAYOUTS.EDRL_TITLE, 
  dbo.ED_RECORDS.EDR_STATE, 
  dbo.ED_RECORDS.RECORD_ID, 
  dbo.ED_RECORDS.EDR_RECORD_DATE, 
  dbo.ED_RECORDS.EDR_COMMENTS, 
  dbo.ED_RECORDS.EDR_SERIAL_ID, 
  dbo.ED_RECORDS.EDR_SOURCE_ID, 
  dbo.ED_RECORDS.EDR_SIGN_OFFS, 
  dbo.ED_RECORDS.EDR_BOOKED_OUT_USER_ID, 
  dbo.ED_RECORDS.EDR_BOOKED_OUT, 
  dbo.ED_RECORDS.EDR_UPDATED_BY_USER_ID, 
  dbo.ED_RECORDS.EDR_UPDATED_BY, 
  dbo.ED_RECORDS.EDR_UPDATED_DATE, 
  dbo.ED_RECORD_LAYOUTS.EDRL_HTTP_REFERENCE, 
  dbo.ED_RECORD_LAYOUTS.EDRL_INSTRUCTIONS, 
  dbo.ED_RECORD_LAYOUTS.EDRL_TYPE_ID, 
  dbo.ED_RECORD_LAYOUTS.EDRL_VERSION, 
  dbo.ED_RECORD_LAYOUTS.EDRL_JAVA_SCRIPT, 
  dbo.ED_RECORD_LAYOUTS.EDRL_HAS_CS_SCRIPT, 
  dbo.ED_RECORD_LAYOUTS.EDRL_LANGUAGE, 
  dbo.ED_RECORD_LAYOUTS.EDRL_RECORD_PREFIX, 
  dbo.ED_RECORD_LAYOUTS.EDRL_CDASH_METADATA, 
  dbo.ED_RECORD_LAYOUTS.EDRL_RECORD_CATEGORY, 
  dbo.ED_RECORD_LAYOUTS.EDRL_UPDATE_REASON, 
  dbo.ED_RECORD_LAYOUTS.EDRL_DESCRIPTION, 
  dbo.ED_RECORDS.EDR_DELETED
FROM   dbo.ED_RECORD_LAYOUTS INNER JOIN
  dbo.ED_RECORDS ON dbo.ED_RECORD_LAYOUTS.EDRL_GUID = dbo.ED_RECORDS.EDRL_GUID
  WHERE dbo.ED_RECORDS.EDR_DELETED = 0

GO

/****** Object:  View [dbo].[ED_RECORD_FILTER_VIEW]    Script Date: 01/08/2021 10:58:14 ******/
CREATE VIEW [dbo].[ED_RECORD_FILTER_VIEW]
AS
SELECT     
  dbo.ED_RECORD_LAYOUTS.CU_GUID, 
  dbo.ED_RECORD_LAYOUTS.EDRL_GUID, 
  dbo.ED_RECORDS.EDR_GUID, 
  dbo.ED_RECORD_LAYOUTS.APPLICATION_ID, 
  dbo.ED_RECORD_LAYOUTS.LAYOUT_ID, 
  dbo.ED_RECORD_LAYOUTS.EDRL_TITLE, 
  dbo.ED_RECORD_LAYOUTS.EDRL_HTTP_REFERENCE, 
  dbo.ED_RECORD_LAYOUTS.EDRL_INSTRUCTIONS, 
  dbo.ED_RECORD_LAYOUTS.EDRL_DESCRIPTION, 
  dbo.ED_RECORD_LAYOUTS.EDRL_UPDATE_REASON, 
  dbo.ED_RECORD_LAYOUTS.EDRL_RECORD_CATEGORY, 
  dbo.ED_RECORD_LAYOUTS.EDRL_TYPE_ID, 
  dbo.ED_RECORD_LAYOUTS.EDRL_VERSION, 
  dbo.ED_RECORD_LAYOUTS.EDRL_JAVA_SCRIPT, 
  dbo.ED_RECORD_LAYOUTS.EDRL_HAS_CS_SCRIPT, 
  dbo.ED_RECORD_LAYOUTS.EDRL_LANGUAGE, 
  dbo.ED_RECORD_LAYOUTS.EDRL_RECORD_PREFIX, 
  dbo.ED_RECORD_LAYOUTS.EDRL_CDASH_METADATA, 
  dbo.ED_RECORD_LAYOUTS.EDRL_UPDATED_BY, 
  dbo.ED_RECORD_LAYOUTS.EDRL_UPDATED_DATE, 
  dbo.ED_RECORDS.EDR_STATE, 
  dbo.ED_RECORDS.RECORD_ID, 
  dbo.ED_RECORDS.EDR_SOURCE_ID, 
  dbo.ED_RECORDS.EDR_COLLECTION_EVENT_ID, 
  dbo.ED_RECORDS.EDR_RECORD_DATE, 
  dbo.ED_RECORDS.EDR_COMMENTS, 
  dbo.ED_RECORDS.EDR_SIGN_OFFS, 
  dbo.ED_RECORDS.EDR_SERIAL_ID, 
  dbo.ED_RECORDS.EDR_BOOKED_OUT_USER_ID, 
  dbo.ED_RECORDS.EDR_BOOKED_OUT, 
  dbo.ED_RECORDS.EDR_UPDATED_BY_USER_ID, 
  dbo.ED_RECORDS.EDR_UPDATED_BY, 
  dbo.ED_RECORD_LAYOUT_FIELDS.FIELD_ID, 
  dbo.ED_RECORD_LAYOUT_FIELDS.EDRLF_TYPE_ID, 
  dbo.ED_RECORD_LAYOUT_FIELDS.EDRLF_TITLE, 
  dbo.ED_RECORD_LAYOUT_FIELDS.EDRLF_OPTIONS, 
  dbo.ED_RECORD_VALUES.EDRV_COLUMN, 
  dbo.ED_RECORD_VALUES.EDRV_ROW, 
  dbo.ED_RECORD_VALUES.EDRV_STRING, 
  dbo.ED_RECORD_VALUES.EDRV_NUMERIC, 
  dbo.ED_RECORD_VALUES.EDRV_DATE, 
  dbo.ED_RECORD_VALUES.EDRV_TEXT
FROM         dbo.ED_RECORDS INNER JOIN
  dbo.ED_RECORD_VALUES ON dbo.ED_RECORDS.EDR_GUID = dbo.ED_RECORD_VALUES.EDR_GUID INNER JOIN
  dbo.ED_RECORD_LAYOUT_FIELDS ON dbo.ED_RECORD_VALUES.EDRLF_GUID = dbo.ED_RECORD_LAYOUT_FIELDS.EDRLF_GUID INNER JOIN
  dbo.ED_RECORD_LAYOUTS ON dbo.ED_RECORDS.EDRL_GUID = dbo.ED_RECORD_LAYOUTS.EDRL_GUID
  WHERE dbo.ED_RECORDS.EDR_DELETED = 0;

GO

/****** Object:  StoredProcedure [dbo].[USR_RECORD_CREATE]    Script Date: 01/07/2021 11:18:08 ******/

CREATE  PROCEDURE [dbo].[USR_RECORD_CREATE]
  @GUID uniqueidentifier ,
	@APPLICATION_ID nvarchar(10),
	@LAYOUT_ID nvarchar(10),
	@UPDATED_BY_USER_ID nvarchar(100) ,
	@UPDATED_BY nvarchar(100) ,
	@UPDATED_DATE datetime 
AS

DECLARE @PREFIX nvarchar(10)
DECLARE @LAYOUT_GUID uniqueidentifier
DECLARE @RECORD_ID nvarchar(20)
DECLARE @SERIAL_ID INT
DECLARE @NEW_SERIAL_ID INT

SELECT 	@LAYOUT_GUID = EDRL_GUID, @PREFIX = EDRL_RECORD_PREFIX  
FROM ED_RECORD_LAYOUT_ISSUED 
WHERE (LAYOUT_ID = @LAYOUT_ID) AND (APPLICATION_ID = @APPLICATION_ID);

IF (@PREFIX ='' )
BEGIN
 SELECT @PREFIX = @APPLICATION_ID;
END 

SET @UPDATED_DATE = GetDate();

SELECT 	@NEW_SERIAL_ID = 1;

SELECT 	@SERIAL_ID = Max(EDR_SERIAL_ID) 
FROM 	ED_RECORD_VIEW 
WHERE (LAYOUT_ID = @LAYOUT_ID) AND (APPLICATION_ID = @APPLICATION_ID);

IF (@SERIAL_ID > 0 )
BEGIN
 SELECT @NEW_SERIAL_ID = @SERIAL_ID + 1;
END 

SELECT @RECORD_ID = @PREFIX + RIGHT( '00000000' + CONVERT(VARCHAR(8), @NEW_SERIAL_ID), 8 );

Insert Into ED_RECORDS 
 ( EDR_GUID
  ,EDRL_GUID
  ,RECORD_ID
  ,EDR_STATE
  ,EDR_SERIAL_ID
  ,EDR_UPDATED_BY_USER_ID
  ,EDR_UPDATED_BY
  ,EDR_UPDATED_DATE
  ,EDR_DELETED ) 
values 
 (@GUID, 
  @LAYOUT_GUID, 
  @RECORD_ID, 
  'Empty_Record', 
  @NEW_SERIAL_ID, 
  @UPDATED_BY_USER_ID,
	@UPDATED_BY,
	@UPDATED_DATE,
  0);

GO

/****** Object:  StoredProcedure [dbo].[USR_RECORD_DELETE]    Script Date: 01/07/2021 11:18:08 ******/

CREATE	PROCEDURE [dbo].[USR_RECORD_DELETE]
  @GUID uniqueidentifier  ,
  @UPDATED_BY_USER_ID nvarchar(100) ,
	@UPDATED_BY nvarchar(100) ,
	@UPDATED_DATE datetime 
AS

UPDATE 	ED_RECORDS 
SET 	
  EDR_UPDATED_BY_USER_ID =  @UPDATED_BY_USER_ID,  
  EDR_UPDATED_BY =  @UPDATED_BY,  
	EDR_UPDATED_DATE = @UPDATED_DATE , 
	EDR_DELETED = 1 
WHERE (EDR_DELETED = 0) 
  AND (EDR_GUID = @Guid) ;




GO


/****** Object:  StoredProcedure [dbo].[USR_RECORD_LOCK]    Script Date: 01/07/2021 11:20:00 ******/

CREATE      PROCEDURE [dbo].[USR_RECORD_LOCK]
  @GUID uniqueidentifier  ,
  @UPDATED_BY_USER_ID nvarchar(100) ,
	@UPDATED_BY nvarchar(100) ,
	@UPDATED_DATE datetime 
AS

UPDATE	ED_RECORDS 
SET 	
  EDR_BOOKED_OUT_USER_ID = @UPDATED_BY_USER_ID,  
  EDR_BOOKED_OUT = @UPDATED_BY,  
  EDR_UPDATED_BY_USER_ID =  @UPDATED_BY_USER_ID,  
  EDR_UPDATED_BY =  @UPDATED_BY,  
	EDR_UPDATED_DATE = @UPDATED_DATE 
WHERE	(EDR_GUID = @GUID) 
  AND (EDR_BOOKED_OUT = '');




GO

/****** Object:  StoredProcedure [dbo].[USR_RECORD_UNLOCK]    Script Date: 01/07/2021 11:20:00 ******/

CREATE PROCEDURE [dbo].[USR_RECORD_UNLOCK]
  @GUID uniqueidentifier  ,
  @UPDATED_BY_USER_ID nvarchar(100) ,
	@UPDATED_BY nvarchar(100) ,
	@UPDATED_DATE datetime 
AS

UPDATE	ED_RECORDS 
SET 	  
  EDR_BOOKED_OUT_USER_ID = '',  
  EDR_BOOKED_OUT = '',  
  EDR_UPDATED_BY_USER_ID =  @UPDATED_BY_USER_ID,  
  EDR_UPDATED_BY =  @UPDATED_BY,  
	EDR_UPDATED_DATE = @UPDATED_DATE 
WHERE	(EDR_GUID = @GUID) ;




GO

/****** Object:  StoredProcedure [dbo].[USR_RECORD_UPDATE]    Script Date: 01/07/2021 11:20:00 ******/

CREATE PROCEDURE [dbo].[USR_RECORD_UPDATE]
  @GUID uniqueidentifier,
	@STATE varchar(30),
	@SOURCE_ID nvarchar(20),
	@RECORD_DATE datetime,
	@COMMENTS ntext,
	@SIGN_OFFS ntext,
	@UPDATED_BY_USER_ID nvarchar(100),
	@UPDATED_BY nvarchar(100),
	@UPDATED_DATE datetime 
AS

UPDATE 	ED_RECORDS 
SET
   EDR_STATE = @STATE
  ,EDR_SOURCE_ID = @SOURCE_ID
  ,EDR_RECORD_DATE = @RECORD_DATE
  ,EDR_COMMENTS = @COMMENTS
  ,EDR_SIGN_OFFS = @SIGN_OFFS
  ,EDR_BOOKED_OUT_USER_ID = ''
  ,EDR_BOOKED_OUT = ''
  ,EDR_UPDATED_BY_USER_ID = @UPDATED_BY_USER_ID
  ,EDR_UPDATED_BY = @UPDATED_BY
  ,EDR_UPDATED_DATE = @UPDATED_DATE
WHERE 	(EDR_GUID = @GUID);

GO





PRINT N'FINISH: 005_R1.0_ED_RECORDs_CREATE_STORED_PROCEDURES.'; 
GO
