/****** File: 008_R1.0_ED_ENTITY_LAYOUTS_CREATE_STORED_PROCEDURES.sql ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

DECLARE @RC int

EXECUTE @RC = dbo.usr_DB_Add_Database_Update 
   008, 'R1.0','ED_ENTITY_LAYOUTS', 
   'CREATE STORED PROCEDURES.'

GO

PRINT N'START: 008_R1.0_ED_ENTITY_LAYOUTS_CREATE_STORED_PROCEDURES.'; 
GO
/****** Object:  StoredProcedure dbo.USR_ENTITY_LAYOUT_ADD    Script Date: 01/04/2021 10:32:51 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.USR_ENTITY_LAYOUT_ADD') AND type in (N'P', N'PC'))
DROP PROCEDURE dbo.USR_ENTITY_LAYOUT_ADD
GO

/****** Object:  StoredProcedure dbo.USR_ENTITY_LAYOUT_COPY    Script Date: 01/04/2021 10:32:51 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.USR_ENTITY_LAYOUT_COPY') AND type in (N'P', N'PC'))
DROP PROCEDURE dbo.USR_ENTITY_LAYOUT_COPY
GO

/****** Object:  StoredProcedure dbo.USR_ENTITY_LAYOUT_DELETE    Script Date: 01/04/2021 10:32:51 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.USR_ENTITY_LAYOUT_DELETE') AND type in (N'P', N'PC'))
DROP PROCEDURE dbo.USR_ENTITY_LAYOUT_DELETE
GO

/****** Object:  StoredProcedure dbo.USR_ENTITY_LAYOUT_UPDATE    Script Date: 01/04/2021 10:32:51 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.USR_ENTITY_LAYOUT_UPDATE') AND type in (N'P', N'PC'))
DROP PROCEDURE dbo.USR_ENTITY_LAYOUT_UPDATE
GO

/****** Object:  StoredProcedure dbo.USR_ENTITY_LAYOUT_WITHDRAWN    Script Date: 01/04/2021 10:32:51 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.USR_ENTITY_LAYOUT_WITHDRAWN') AND type in (N'P', N'PC'))
DROP PROCEDURE dbo.USR_ENTITY_LAYOUT_WITHDRAWN
GO

/****** Object:  View dbo.ED_ENTITY_LAYOUT_VIEW    Script Date: 01/05/2021 10:02:06 ******/
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'dbo.ED_ENTITY_LAYOUT_VIEW'))
DROP VIEW dbo.ED_ENTITY_LAYOUT_VIEW
GO

/****** Object:  View [dbo].[ED_ENTITY_LAYOUT_ISSUED]    Script Date: 01/07/2021 11:24:29 ******/
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ED_ENTITY_LAYOUT_ISSUED]'))
DROP VIEW [dbo].[ED_ENTITY_LAYOUT_ISSUED]
GO

/****** Object:  View dbo.ED_ENTITY_LAYOUT_VIEW    Script Date: 01/05/2021 10:02:06 ******/
CREATE VIEW dbo.ED_ENTITY_LAYOUT_VIEW
AS
SELECT 
   [EDEL_GUID]
  ,[EDE_LAYOUT_ID]
  ,[EDEL_STATE]
  ,[EDEL_TYPE_ID]
  ,[EDEL_TITLE]
  ,[EDEL_HTTP_REFERENCE]
  ,[EDEL_INSTRUCTIONS]
  ,[EDEL_DESCRIPTION]
  ,[EDEL_UPDATE_REASON]
  ,[EDEL_RECORD_CATEGORY]
  ,[EDEL_VERSION]
  ,[EDEL_JAVA_SCRIPT]
  ,[EDEL_HAS_CS_SCRIPT]
  ,[EDEL_LANGUAGE]
  ,[EDEL_ENTITY_PREFIX]
  ,[EDEL_READ_ACCESS_ROLES]
  ,[EDEL_EDIT_ACCESS_ROLES]
  ,[EDEL_PARENT_TYPE]
  ,[EDEL_PARENT_ACCESS]
  ,[EDEL_PARENT_ENTITIES]
  ,[EDEL_LINK_CONTENT_SETTING]
  ,[EDEL_DEFAULT_PAGE_LAYOUT]
  ,[EDEL_DISPLAY_ENTITIES]
  ,[EDEL_DISPLAY_AUTHOR_DETAILS]
  ,[EDEL_HEADER_FORMAT]
  ,[EDEL_FOOTER_FORMAT]
  ,[EDEL_FIELD_DISPLAY_FORMAT]
  ,[EDEL_FILTER_FIELD_0]
  ,[EDEL_FILTER_FIELD_1]
  ,[EDEL_FILTER_FIELD_2]
  ,[EDEL_FILTER_FIELD_3]
  ,[EDEL_FILTER_FIELD_4]
  ,[EDEL_UPDATED_BY_USER_ID]
  ,[EDEL_UPDATED_BY]
  ,[EDEL_UPDATED_DATE]
  ,[EDEL_DELETED]
FROM  ED_ENTITY_LAYOUTS
WHERE     (EDEL_DELETED = 0)

GO
/****** Object:  View [dbo].[ED_ENTITY_LAYOUT_ISSUED]    Script Date: 01/07/2021 11:24:29 ******/

CREATE VIEW [dbo].[ED_ENTITY_LAYOUT_ISSUED]
AS
SELECT     
   [EDEL_GUID]
  ,[EDE_LAYOUT_ID]
  ,[EDEL_STATE]
  ,[EDEL_TYPE_ID]
  ,[EDEL_TITLE]
  ,[EDEL_HTTP_REFERENCE]
  ,[EDEL_INSTRUCTIONS]
  ,[EDEL_DESCRIPTION]
  ,[EDEL_UPDATE_REASON]
  ,[EDEL_RECORD_CATEGORY]
  ,[EDEL_VERSION]
  ,[EDEL_JAVA_SCRIPT]
  ,[EDEL_HAS_CS_SCRIPT]
  ,[EDEL_LANGUAGE]
  ,[EDEL_ENTITY_PREFIX]
  ,[EDEL_READ_ACCESS_ROLES]
  ,[EDEL_EDIT_ACCESS_ROLES]
  ,[EDEL_PARENT_TYPE]
  ,[EDEL_PARENT_ACCESS]
  ,[EDEL_PARENT_ENTITIES]
  ,[EDEL_LINK_CONTENT_SETTING]
  ,[EDEL_DEFAULT_PAGE_LAYOUT]
  ,[EDEL_DISPLAY_ENTITIES]
  ,[EDEL_DISPLAY_AUTHOR_DETAILS]
  ,[EDEL_HEADER_FORMAT]
  ,[EDEL_FOOTER_FORMAT]
  ,[EDEL_FIELD_DISPLAY_FORMAT]
  ,[EDEL_FILTER_FIELD_0]
  ,[EDEL_FILTER_FIELD_1]
  ,[EDEL_FILTER_FIELD_2]
  ,[EDEL_FILTER_FIELD_3]
  ,[EDEL_FILTER_FIELD_4]
  ,[EDEL_UPDATED_BY_USER_ID]
  ,[EDEL_UPDATED_BY]
  ,[EDEL_UPDATED_DATE]
  ,[EDEL_DELETED]
FROM        ED_ENTITY_LAYOUTS
WHERE     (EDEL_DELETED = 0) AND (EDEL_STATE = 'Form_Issued')

GO



/****** Object:  StoredProcedure dbo.USR_ENTITY_LAYOUT_ADD    Script Date: 01/04/2021 10:32:51 ******/
CREATE PROCEDURE dbo.USR_ENTITY_LAYOUT_ADD
 @GUID UniqueIdentifier,
 @LAYOUT_ID NVarChar(20),
 @STATE  NVarChar(20),
 @TITLE NVarChar(80),
 @HTTP_REFERENCE NVarChar(250),
 @INSTRUCTIONS NText,
 @DESCRIPTION NText,   
 @UPDATE_REASON  NVarChar(50),
 @RECORD_CATEGORY NVarChar(100),
 @TYPE_ID VarChar(25),
 @VERSION Float,
 @JAVA_SCRIPT NText,   
 @HAS_CS_SCRIPT Bit,
 @LANGUAGE VarChar(5),
 @ENTITY_PREFIX VarChar(5),
 @READ_ACCESS_ROLES NVarChar(250),
 @EDIT_ACCESS_ROLES NVarChar(250),
 @PARENT_TYPE NVARCHAR(50),
 @DEFAULT_PAGE_LAYOUT NVARCHAR(50),
 @PARENT_ENTITIES NVARCHAR(250),
 @PARENT_ACCESS NVARCHAR(50),
 @LINK_CONTENT_SETTING NVARCHAR(50),
 @DISPLAY_ENTITIES BIT,
 @DISPLAY_AUTHOR_DETAILS BIT,
 @HEADER_FORMAT NVARCHAR(30),
 @FOOTER_FORMAT NVARCHAR(30),
 @FIELD_DISPLAY_FORMAT NVarChar(50),
 @FILTER_FIELD_0  NVARCHAR(30),
 @FILTER_FIELD_1  NVARCHAR(30),
 @FILTER_FIELD_2  NVARCHAR(30),
 @FILTER_FIELD_3  NVARCHAR(30),
 @FILTER_FIELD_4  NVARCHAR(30),
 @UPDATED_BY_USER_ID NVarChar(100),
 @UPDATED_BY NVarChar(30),
 @UPDATED_DATE DateTime
AS

Insert Into ED_ENTITY_LAYOUTS 
  (EDEL_GUID
  ,EDE_LAYOUT_ID
  ,EDEL_STATE
  ,EDEL_TYPE_ID
  ,EDEL_TITLE
  ,EDEL_HTTP_REFERENCE
  ,EDEL_INSTRUCTIONS
  ,EDEL_DESCRIPTION
  ,EDEL_UPDATE_REASON
  ,EDEL_RECORD_CATEGORY
  ,EDEL_VERSION
  ,EDEL_JAVA_SCRIPT
  ,EDEL_HAS_CS_SCRIPT
  ,EDEL_LANGUAGE
  ,EDEL_ENTITY_PREFIX
  ,EDEL_READ_ACCESS_ROLES
  ,EDEL_EDIT_ACCESS_ROLES
  ,EDEL_PARENT_TYPE
  ,EDEL_PARENT_ACCESS
  ,EDEL_PARENT_ENTITIES
  ,EDEL_LINK_CONTENT_SETTING
  ,EDEL_DEFAULT_PAGE_LAYOUT
  ,EDEL_DISPLAY_ENTITIES
  ,EDEL_DISPLAY_AUTHOR_DETAILS
  ,EDEL_HEADER_FORMAT
  ,EDEL_FOOTER_FORMAT
  ,EDEL_FIELD_DISPLAY_FORMAT
  ,EDEL_FILTER_FIELD_0
  ,EDEL_FILTER_FIELD_1
  ,EDEL_FILTER_FIELD_2
  ,EDEL_FILTER_FIELD_3
  ,EDEL_FILTER_FIELD_4
  ,EDEL_UPDATED_BY_USER_ID
  ,EDEL_UPDATED_BY
  ,EDEL_UPDATED_DATE
  ,EDEL_DELETED  ) 
values 
 ( @GUID
  ,@LAYOUT_ID
  ,@STATE
  ,@TYPE_ID
  ,@TITLE
  ,@HTTP_REFERENCE
  ,@INSTRUCTIONS
  ,@DESCRIPTION
  ,@UPDATE_REASON
  ,@RECORD_CATEGORY
  ,@VERSION
  ,@JAVA_SCRIPT
  ,@HAS_CS_SCRIPT
  ,@LANGUAGE
  ,@ENTITY_PREFIX
  ,@READ_ACCESS_ROLES
  ,@EDIT_ACCESS_ROLES
  ,@PARENT_TYPE
  ,@PARENT_ACCESS
  ,@PARENT_ENTITIES
  ,@LINK_CONTENT_SETTING
  ,@DEFAULT_PAGE_LAYOUT
  ,@DISPLAY_ENTITIES
  ,@DISPLAY_AUTHOR_DETAILS
  ,@HEADER_FORMAT
  ,@FOOTER_FORMAT
  ,@FIELD_DISPLAY_FORMAT
  ,@FILTER_FIELD_0
  ,@FILTER_FIELD_1
  ,@FILTER_FIELD_2
  ,@FILTER_FIELD_3
  ,@FILTER_FIELD_4
  ,@UPDATED_BY_USER_ID
  ,@UPDATED_BY
  ,@UPDATED_DATE,0  );

GO

/****** Object:  StoredProcedure dbo.USR_ENTITY_LAYOUT_COPY    Script Date: 01/04/2021 10:32:51 ******/

CREATE PROCEDURE dbo.USR_ENTITY_LAYOUT_COPY
 @GUID UniqueIdentifier,
 @LAYOUT_ID NVarChar(20),
 @TITLE NVarChar(100),
 @VERSION Float,
 @UPDATED_BY_USER_ID NVarChar(100),
 @UPDATED_BY NVarChar(30),
 @UPDATED_DATE DateTime
AS

DECLARE @NEW_GUID uniqueidentifier

SET @NEW_GUID =  newid()

/** COPY THE FORM CVALUES IN TO THE FORM OBJECT.**/
Insert Into ED_ENTITY_LAYOUTS 
  ( EDEL_GUID
  ,EDE_LAYOUT_ID
  ,EDEL_STATE
  ,EDEL_TITLE
  ,EDEL_TYPE_ID
  ,EDEL_HTTP_REFERENCE
  ,EDEL_INSTRUCTIONS
  ,EDEL_DESCRIPTION
  ,EDEL_UPDATE_REASON
  ,EDEL_RECORD_CATEGORY
  ,EDEL_VERSION
  ,EDEL_JAVA_SCRIPT
  ,EDEL_HAS_CS_SCRIPT
  ,EDEL_LANGUAGE
  ,EDEL_ENTITY_PREFIX
  ,EDEL_READ_ACCESS_ROLES
  ,EDEL_EDIT_ACCESS_ROLES
  ,EDEL_PARENT_TYPE
  ,EDEL_PARENT_ACCESS
  ,EDEL_PARENT_ENTITIES
  ,EDEL_LINK_CONTENT_SETTING
  ,EDEL_DEFAULT_PAGE_LAYOUT
  ,EDEL_DISPLAY_ENTITIES
  ,EDEL_DISPLAY_AUTHOR_DETAILS
  ,EDEL_HEADER_FORMAT
  ,EDEL_FOOTER_FORMAT
  ,EDEL_FIELD_DISPLAY_FORMAT
  ,EDEL_FILTER_FIELD_0
  ,EDEL_FILTER_FIELD_1
  ,EDEL_FILTER_FIELD_2
  ,EDEL_FILTER_FIELD_3
  ,EDEL_FILTER_FIELD_4
  ,EDEL_UPDATED_BY_USER_ID
  ,EDEL_UPDATED_BY
  ,EDEL_UPDATED_DATE
  ,EDEL_DELETED  ) 
SELECT 
   @NEW_GUID
  ,@LAYOUT_ID 
  ,'Form_Draft'
  ,@TITLE 
  ,EDEL_TYPE_ID
  ,EDEL_HTTP_REFERENCE
  ,EDEL_INSTRUCTIONS
  ,EDEL_DESCRIPTION
  ,EDEL_UPDATE_REASON
  ,EDEL_RECORD_CATEGORY
  ,@VERSION
  ,EDEL_JAVA_SCRIPT
  ,EDEL_HAS_CS_SCRIPT
  ,EDEL_LANGUAGE
  ,EDEL_ENTITY_PREFIX
  ,EDEL_READ_ACCESS_ROLES
  ,EDEL_EDIT_ACCESS_ROLES
  ,EDEL_PARENT_TYPE
  ,EDEL_PARENT_ACCESS
  ,EDEL_PARENT_ENTITIES
  ,EDEL_LINK_CONTENT_SETTING
  ,EDEL_DEFAULT_PAGE_LAYOUT
  ,EDEL_DISPLAY_ENTITIES
  ,EDEL_DISPLAY_AUTHOR_DETAILS
  ,EDEL_HEADER_FORMAT
  ,EDEL_FOOTER_FORMAT 
  ,EDEL_FIELD_DISPLAY_FORMAT
  ,EDEL_FILTER_FIELD_0
  ,EDEL_FILTER_FIELD_1
  ,EDEL_FILTER_FIELD_2
  ,EDEL_FILTER_FIELD_3
  ,EDEL_FILTER_FIELD_4
  ,@UPDATED_BY_USER_ID
  ,@UPDATED_BY
  ,@UPDATED_DATE
  , 0
FROM ED_ENTITY_LAYOUTS 
WHERE (EDEL_GUID = @GUID);


/** COPY THE FORM SECTION IN TO THE FORM OBJECT.**/
INSERT INTO ED_ENTITY_SECTIONS 
 ( EDEL_GUID 
  ,EDELS_NUMBER 
  ,EDELS_ORDER 
  ,EDELS_NAME 
  ,EDELS_INSTRUCTIONS 
  ,EDELS_FIELD_NAME 
  ,EDELS_FIELD_VALUE 
  ,EDELS_ON_MATCH_VISIBLE 
  ,EDELS_VISIBLE 
  ,EDELS_DEFAULT_DISPLAY_ROLES 
  ,EDELS_DEFAULT_EDIT_ROLES ) 
SELECT 
  @NEW_GUID
  ,EDELS_NUMBER 
  ,EDELS_ORDER 
  ,EDELS_NAME 
  ,EDELS_INSTRUCTIONS 
  ,EDELS_FIELD_NAME 
  ,EDELS_FIELD_VALUE 
  ,EDELS_ON_MATCH_VISIBLE 
  ,EDELS_VISIBLE 
  ,EDELS_DEFAULT_DISPLAY_ROLES 
  ,EDELS_DEFAULT_EDIT_ROLES
FROM ED_ENTITY_SECTIONS 
WHERE (EDEL_GUID = @GUID);

/** COPY THE FORM FIELDS INTO THE NEW FORM OBJECT.**/
INSERT INTO ED_ENTITY_FIELDS 
 ( EDEL_GUID 
  , EDELF_GUID 
  , EDE_LAYOUT_ID 
  , EDELF_FIELD_ID 
  , EDELF_TYPE_ID 
  , EDELF_ORDER 
  , EDELF_TITLE 
  , EDELF_INSTRUCTIONS 
  , EDELF_HTTP_REFERENCE 
  , EDELF_SECTION_ID 
  , EDELF_OPTIONS 
  , EDELF_SUMMARY_FIELD 
  , EDELF_MANDATORY 
  , EDELF_AI_DATA_POINT 
  , EDELF_HIDDEN 
  , EDELF_ANALYTICS_DATA_POINT
  , EDELF_DEFAULT_VALUE 
  , EDELF_UNIT 
  , EDELF_UNIT_SCALING 
  , EDELF_VALIDATION_LOWER_LIMIT 
  , EDELF_VALIDATION_UPPER_LIMIT 
  , EDELF_ALERT_LOWER_LIMIT 
  , EDELF_ALERT_UPPER_LIMIT 
  , EDELF_NORMAL_LOWER_LIMIT 
  , EDELF_NORMAL_UPPER_LIMIT 
  , EDELF_FIELD_CATEGORY 
  , EDELF_ANALOGUE_LEGEND_START 
  , EDELF_ANALOGUE_LEGEND_FINISH 
  , EDELF_JAVA_SCRIPT 
  , EDELF_TABLE 
  , EDELF_INITIAL_OPTION_LIST 
  , EDELF_FIELD_LAYOUT 
  , EDELF_INITIAL_VERSION 
  , EDELF_DELETED  ) 
SELECT 
   @NEW_GUID
  , NEWID()
  , EDE_LAYOUT_ID
  , EDELF_FIELD_ID 
  , EDELF_TYPE_ID 
  , EDELF_ORDER 
  , EDELF_TITLE 
  , EDELF_INSTRUCTIONS 
  , EDELF_HTTP_REFERENCE 
  , EDELF_SECTION_ID 
  , EDELF_OPTIONS 
  , EDELF_SUMMARY_FIELD 
  , EDELF_MANDATORY 
  , EDELF_AI_DATA_POINT
  , EDELF_ANALYTICS_DATA_POINT
  , EDELF_HIDDEN 
  , EDELF_DEFAULT_VALUE 
  , EDELF_UNIT 
  , EDELF_UNIT_SCALING 
  , EDELF_VALIDATION_LOWER_LIMIT 
  , EDELF_VALIDATION_UPPER_LIMIT 
  , EDELF_ALERT_LOWER_LIMIT 
  , EDELF_ALERT_UPPER_LIMIT 
  , EDELF_NORMAL_LOWER_LIMIT 
  , EDELF_NORMAL_UPPER_LIMIT 
  , EDELF_FIELD_CATEGORY 
  , EDELF_ANALOGUE_LEGEND_START 
  , EDELF_ANALOGUE_LEGEND_FINISH 
  , EDELF_JAVA_SCRIPT 
  , EDELF_TABLE 
  , EDELF_INITIAL_OPTION_LIST 
  , EDELF_FIELD_LAYOUT 
  , EDELF_INITIAL_VERSION 
  ,0
  FROM   ED_ENTITY_FIELDS 
WHERE (EDEL_GUID = @GUID) and (EDELF_DELETED = 0);

GO

/****** Object:  StoredProcedure dbo.USR_ENTITY_LAYOUT_DELETE    Script Date: 01/04/2021 10:32:51 ******/

CREATE   PROCEDURE dbo.USR_ENTITY_LAYOUT_DELETE 
 @GUID UniqueIdentifier ,
 @UPDATED_BY_USER_ID NVarChar (100),
 @UPDATED_BY  NVarChar(30),
 @UPDATED_DATE DateTime
AS

UPDATE ED_ENTITY_LAYOUTS 
SET 
  EDEL_UPDATED_BY_USER_ID = @UPDATED_BY_USER_ID,  
  EDEL_UPDATED_BY = @UPDATED_BY,  
  EDEL_UPDATED_DATE = @UPDATED_DATE, 
  EDEL_DELETED = -1 
WHERE 	EDEL_DELETED = 0 
	AND EDEL_GUID = @GUID ;

GO

/****** Object:  StoredProcedure dbo.USR_ENTITY_LAYOUT_UPDATE    Script Date: 01/04/2021 10:32:51 ******/

CREATE PROCEDURE dbo.USR_ENTITY_LAYOUT_UPDATE
 @GUID UniqueIdentifier,
 @LAYOUT_ID NVarChar(20),
 @STATE  NVarChar(20),
 @TITLE NVarChar(80),
 @HTTP_REFERENCE NVarChar(250),
 @INSTRUCTIONS NText,
 @DESCRIPTION NText,   
 @UPDATE_REASON  NVarChar(50),
 @RECORD_CATEGORY NVarChar(100),
 @ENTITY_PREFIX NVarChar(5),
 @TYPE_ID VarChar(25),
 @VERSION Float,
 @JAVA_SCRIPT NText,   
 @HAS_CS_SCRIPT Bit,
 @LANGUAGE VarChar(5),
 @READ_ACCESS_ROLES NVarChar(250),
 @EDIT_ACCESS_ROLES NVarChar(250),
 @PARENT_TYPE NVARCHAR(50),
 @DEFAULT_PAGE_LAYOUT NVARCHAR(50),
 @PARENT_ENTITIES NVARCHAR(250),
 @PARENT_ACCESS NVARCHAR(50),
 @LINK_CONTENT_SETTING NVARCHAR(50),
 @DISPLAY_ENTITIES BIT,
 @DISPLAY_AUTHOR_DETAILS BIT,
 @HEADER_FORMAT NVARCHAR(30),
 @FOOTER_FORMAT NVARCHAR(30),
 @FIELD_DISPLAY_FORMAT NVarChar(50),
 @FILTER_FIELD_0  NVARCHAR(20),
 @FILTER_FIELD_1  NVARCHAR(30),
 @FILTER_FIELD_2  NVARCHAR(30),
 @FILTER_FIELD_3  NVARCHAR(30),
 @FILTER_FIELD_4  NVARCHAR(30),
 @UPDATED_BY_USER_ID NVarChar(100),
 @UPDATED_BY NVarChar(30),
 @UPDATED_DATE DateTime
AS
UPDATE ED_ENTITY_LAYOUTS 
SET 
  EDE_LAYOUT_ID = @LAYOUT_ID ,
  EDEL_STATE = @STATE  ,
  EDEL_TITLE = @TITLE ,
  EDEL_HTTP_REFERENCE = @HTTP_REFERENCE ,
  EDEL_INSTRUCTIONS = @INSTRUCTIONS ,
  EDEL_DESCRIPTION = @DESCRIPTION ,
  EDEL_UPDATE_REASON = @UPDATE_REASON  ,
  EDEL_RECORD_CATEGORY = @RECORD_CATEGORY,
  EDEL_ENTITY_PREFIX = @ENTITY_PREFIX,
  EDEL_TYPE_ID = @TYPE_ID ,
  EDEL_VERSION = @VERSION,
  EDEL_JAVA_SCRIPT = @JAVA_SCRIPT, 
  EDEL_HAS_CS_SCRIPT = @HAS_CS_SCRIPT,
  EDEL_LANGUAGE = @LANGUAGE,
  EDEL_READ_ACCESS_ROLES = @READ_ACCESS_ROLES,
  EDEL_EDIT_ACCESS_ROLES = @EDIT_ACCESS_ROLES,
  EDEL_PARENT_TYPE = @PARENT_TYPE,
  EDEL_PARENT_ENTITIES = @PARENT_ENTITIES,
  EDEL_PARENT_ACCESS = @PARENT_ACCESS,
  EDEL_DEFAULT_PAGE_LAYOUT = @DEFAULT_PAGE_LAYOUT,
  EDEL_LINK_CONTENT_SETTING = @LINK_CONTENT_SETTING,
  EDEL_DISPLAY_ENTITIES = @DISPLAY_ENTITIES,
  EDEL_DISPLAY_AUTHOR_DETAILS = @DISPLAY_AUTHOR_DETAILS,
  EDEL_HEADER_FORMAT = @HEADER_FORMAT,
  EDEL_FOOTER_FORMAT = @FOOTER_FORMAT,
  EDEL_FIELD_DISPLAY_FORMAT = @FIELD_DISPLAY_FORMAT,
  EDEL_FILTER_FIELD_0 = @FILTER_FIELD_0,
  EDEL_FILTER_FIELD_1 = @FILTER_FIELD_1,
  EDEL_FILTER_FIELD_2 = @FILTER_FIELD_2,
  EDEL_FILTER_FIELD_3 = @FILTER_FIELD_3,
  EDEL_FILTER_FIELD_4 = @FILTER_FIELD_4,
  EDEL_UPDATED_BY_USER_ID = @UPDATED_BY_USER_ID,
  EDEL_UPDATED_BY = @UPDATED_BY,
  EDEL_UPDATED_DATE =@UPDATED_DATE
WHERE (EDEL_GUID = @GUID) ;


GO

/****** Object:  StoredProcedure dbo.USR_ENTITY_LAYOUT_UPDATE    Script Date: 01/04/2021 10:32:52 ******/

CREATE PROCEDURE dbo.USR_ENTITY_LAYOUT_WITHDRAWN
 @LAYOUT_ID NVarChar(20),
 @UPDATED_BY_USER_ID NVarChar (100),
 @UPDATED_BY  NVarChar(30),
 @UPDATED_DATE DateTime
AS
UPDATE ED_ENTITY_LAYOUTS 
SET 
  EDEL_STATE = 'Withdrawn', 
  EDEL_UPDATED_BY_USER_ID = @UPDATED_BY_USER_ID,
  EDEL_UPDATED_BY = @UPDATED_BY,
  EDEL_UPDATED_DATE =@UPDATED_DATE
WHERE (EDE_LAYOUT_ID = @LAYOUT_ID)
  AND (EDEL_STATE = 'Form_Issued' ) ;



GO




PRINT N'FINISH: 008_R1.0_ED_ENTITY_LAYOUTS_CREATE_STORED_PROCEDURES.'; 
GO
