/****** File: 008_R1.0_ED_ENTITY_LAYOUTS_CREATE_STORED_PROCEDURES.sql ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

DECLARE @RC int

EXECUTE @RC = dbo.usr_DB_Add_Database_Update 
   008, 'R1.0','ED_ENTITY_LAYOUTS', 
   'CREATE STORED PROCEDURES.'

GO

PRINT N'START: 008_R1.0_ED_ENTITY_LAYOUTS_CREATE_STORED_PROCEDURES.'; 
GO

/****** Object:  StoredProcedure dbo.USR_ENTITY_LAYOUT_ADD    Script Date: 01/04/2021 10:32:51 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.USR_ENTITY_LAYOUT_ADD') AND type in (N'P', N'PC'))
DROP PROCEDURE dbo.USR_ENTITY_LAYOUT_ADD
GO

/****** Object:  StoredProcedure dbo.USR_ENTITY_LAYOUT_COPY    Script Date: 01/04/2021 10:32:51 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.USR_ENTITY_LAYOUT_COPY') AND type in (N'P', N'PC'))
DROP PROCEDURE dbo.USR_ENTITY_LAYOUT_COPY
GO

/****** Object:  StoredProcedure dbo.USR_ENTITY_LAYOUT_DELETE    Script Date: 01/04/2021 10:32:51 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.USR_ENTITY_LAYOUT_DELETE') AND type in (N'P', N'PC'))
DROP PROCEDURE dbo.USR_ENTITY_LAYOUT_DELETE
GO

/****** Object:  StoredProcedure dbo.USR_ENTITY_LAYOUT_UPDATE    Script Date: 01/04/2021 10:32:51 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.USR_ENTITY_LAYOUT_UPDATE') AND type in (N'P', N'PC'))
DROP PROCEDURE dbo.USR_ENTITY_LAYOUT_UPDATE
GO

/****** Object:  StoredProcedure dbo.USR_ENTITY_LAYOUT_WITHDRAWN    Script Date: 01/04/2021 10:32:51 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.USR_ENTITY_LAYOUT_WITHDRAWN') AND type in (N'P', N'PC'))
DROP PROCEDURE dbo.USR_ENTITY_LAYOUT_WITHDRAWN
GO

/****** Object:  View dbo.ED_ENTITY_LAYOUT_VIEW    Script Date: 01/05/2021 10:02:06 ******/
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'dbo.ED_ENTITY_LAYOUT_VIEW'))
DROP VIEW dbo.ED_ENTITY_LAYOUT_VIEW
GO

/****** Object:  View [dbo].[ED_ENTITY_LAYOUT_ISSUED]    Script Date: 01/07/2021 11:24:29 ******/
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ED_ENTITY_LAYOUT_ISSUED]'))
DROP VIEW [dbo].[ED_ENTITY_LAYOUT_ISSUED]
GO

/****** Object:  View dbo.ED_ENTITY_LAYOUT_VIEW    Script Date: 01/05/2021 10:02:06 ******/
CREATE VIEW dbo.ED_ENTITY_LAYOUT_VIEW
AS
SELECT 
   EDEL_GUID
  ,EDE_LAYOUT_ID
  ,EDEL_STATE
  ,EDEL_TITLE
  ,EDEL_HTTP_REFERENCE
  ,EDEL_INSTRUCTIONS
  ,EDEL_DESCRIPTION
  ,EDEL_UPDATE_REASON
  ,EDEL_RECORD_CATEGORY
  ,EDEL_TYPE_ID
  ,EDEL_VERSION
  ,EDEL_JAVA_SCRIPT
  ,EDEL_HAS_CS_SCRIPT
  ,EDEL_LANGUAGE
  ,EDEL_CDASH_METADATA
  ,EDEL_READ_ACCESS_ROLES
  ,EDEL_EDIT_ACCESS_ROLES
  ,EDEL_RELATED_ENTITIES
  ,EDEL_DEFAULT_PAGE_LAYOUT
  ,EDEL_LINK_CONTENT_SETTING
  ,EDEL_DISPLAY_ENTITIES
  ,EDEL_DISPLAY_AUTHOR_DETAILS
  ,EDEL_RECORD_PREFIX
  ,EDEL_AUTHOR_ONLY_EDIT_ACCESS
  ,EDEL_AUTHOR_ONLY_DRAFT_ACCESS
  ,EDEL_UPDATED_BY_USER_ID
  ,EDEL_UPDATED_BY
  ,EDEL_UPDATED_DATE
  ,EDEL_DELETED
FROM        ED_ENTITY_LAYOUTS
WHERE     (EDEL_DELETED = 0)

GO
/****** Object:  View [dbo].[ED_ENTITY_LAYOUT_ISSUED]    Script Date: 01/07/2021 11:24:29 ******/

CREATE VIEW [dbo].[ED_ENTITY_LAYOUT_ISSUED]
AS
SELECT     
   EDEL_GUID
  ,EDE_LAYOUT_ID
  ,EDEL_STATE
  ,EDEL_TITLE
  ,EDEL_HTTP_REFERENCE
  ,EDEL_INSTRUCTIONS
  ,EDEL_DESCRIPTION
  ,EDEL_UPDATE_REASON
  ,EDEL_RECORD_CATEGORY
  ,EDEL_TYPE_ID
  ,EDEL_VERSION
  ,EDEL_JAVA_SCRIPT
  ,EDEL_HAS_CS_SCRIPT
  ,EDEL_LANGUAGE
  ,EDEL_RECORD_PREFIX
  ,EDEL_CDASH_METADATA
  ,EDEL_READ_ACCESS_ROLES
  ,EDEL_EDIT_ACCESS_ROLES
  ,EDEL_RELATED_ENTITIES
  ,EDEL_DEFAULT_PAGE_LAYOUT
  ,EDEL_LINK_CONTENT_SETTING
  ,EDEL_DISPLAY_ENTITIES
  ,EDEL_DISPLAY_AUTHOR_DETAILS
  ,EDEL_AUTHOR_ONLY_EDIT_ACCESS
  ,EDEL_AUTHOR_ONLY_DRAFT_ACCESS
  ,EDEL_UPDATED_BY_USER_ID
  ,EDEL_UPDATED_BY
  ,EDEL_UPDATED_DATE
  ,EDEL_DELETED
FROM        ED_ENTITY_LAYOUTS
WHERE     (EDEL_DELETED = 0) AND (EDEL_STATE = 'Form_Issued')

GO



/****** Object:  StoredProcedure dbo.USR_ENTITY_LAYOUT_ADD    Script Date: 01/04/2021 10:32:51 ******/
CREATE PROCEDURE dbo.USR_ENTITY_LAYOUT_ADD
 @GUID UniqueIdentifier,
 @LAYOUT_ID NVarChar(20),
 @STATE  NVarChar(20),
 @TITLE NVarChar(80),
 @HTTP_REFERENCE NVarChar(250),
 @INSTRUCTIONS NText,
 @DESCRIPTION NText,   
 @UPDATE_REASON  NVarChar(50),
 @RECORD_CATEGORY NVarChar(100),
 @RECORD_PREFIX NVarChar(5),
 @TYPE_ID VarChar(25),
 @VERSION Float,
 @JAVA_SCRIPT NText,   
 @HAS_CS_SCRIPT Bit,
 @LANGUAGE VarChar(5),
 @CDASH_METADATA NVarChar(250),
 @READ_ACCESS_ROLES NVarChar(250),
 @EDIT_ACCESS_ROLES NVarChar(250),
 @RELATED_ENTITIES NVARCHAR(250),
 @DEFAULT_PAGE_LAYOUT NVARCHAR(50),
 @LINK_CONTENT_SETTING NVARCHAR(50),
 @DISPLAY_ENTITIES BIT,
 @DISPLAY_AUTHOR_DETAILS BIT,
 @AUTHOR_ONLY_EDIT_ACCESS BIT,
 @AUTHOR_ONLY_DRAFT_ACCESS BIT,
 @UPDATED_BY_USER_ID NVarChar(100),
 @UPDATED_BY NVarChar(30),
 @UPDATED_DATE DateTime
AS

Insert Into ED_ENTITY_LAYOUTS 
  ( EDEL_GUID 
  , EDE_LAYOUT_ID 
  , EDEL_STATE 
  , EDEL_TITLE 
  , EDEL_HTTP_REFERENCE 
  , EDEL_INSTRUCTIONS 
  , EDEL_DESCRIPTION 
  , EDEL_UPDATE_REASON 
  , EDEL_RECORD_CATEGORY
  , EDEL_RECORD_PREFIX
  , EDEL_TYPE_ID 
  , EDEL_VERSION 
  , EDEL_JAVA_SCRIPT 
  , EDEL_HAS_CS_SCRIPT 
  , EDEL_LANGUAGE 
  , EDEL_CDASH_METADATA 
  , EDEL_READ_ACCESS_ROLES
  , EDEL_EDIT_ACCESS_ROLES
  , EDEL_RELATED_ENTITIES
  , EDEL_DEFAULT_PAGE_LAYOUT
  , EDEL_LINK_CONTENT_SETTING
  , EDEL_DISPLAY_ENTITIES
  , EDEL_DISPLAY_AUTHOR_DETAILS
  , EDEL_AUTHOR_ONLY_EDIT_ACCESS
  , EDEL_AUTHOR_ONLY_DRAFT_ACCESS
  , EDEL_UPDATED_BY_USER_ID 
  , EDEL_UPDATED_BY 
  , EDEL_UPDATED_DATE 
  , EDEL_DELETED  ) 
values 
 ( @GUID,
   @LAYOUT_ID,
   @STATE,
   @TITLE,
   @HTTP_REFERENCE,
   @INSTRUCTIONS,
   @DESCRIPTION,
   @UPDATE_REASON,
   @RECORD_CATEGORY,
   @RECORD_PREFIX,
   @TYPE_ID,
   @VERSION,
   @JAVA_SCRIPT,
   @HAS_CS_SCRIPT,
   @LANGUAGE,
   @CDASH_METADATA,
   @READ_ACCESS_ROLES,
   @EDIT_ACCESS_ROLES,
   @RELATED_ENTITIES,
   @DEFAULT_PAGE_LAYOUT,
   @LINK_CONTENT_SETTING,
   @DISPLAY_ENTITIES,
   @DISPLAY_AUTHOR_DETAILS,
   @AUTHOR_ONLY_EDIT_ACCESS,
   @AUTHOR_ONLY_DRAFT_ACCESS,
   @UPDATED_BY_USER_Id ,
   @UPDATED_BY,
   @UPDATED_DATE,0  );

GO

/****** Object:  StoredProcedure dbo.USR_ENTITY_LAYOUT_COPY    Script Date: 01/04/2021 10:32:51 ******/

CREATE PROCEDURE dbo.USR_ENTITY_LAYOUT_COPY
 @GUID UniqueIdentifier,
 @VERSION Float,
 @Copy bit,
 @UPDATED_BY_USER_ID NVarChar(100),
 @UPDATED_BY NVarChar(30),
 @UPDATED_DATE DateTime
AS

DECLARE @NewGuid uniqueidentifier
DECLARE @LAYOUT_id varchar(20)
DECLARE @Title varchar(100)
DECLARE @CopyId varchar(4)

SET @NewGuid =  newid()

/***** Revise the form  ****/
SELECT @LAYOUT_ID = @LAYOUT_ID,  @Title = EDEL_TITLE 
FROM ED_ENTITY_LAYOUTS 
WHERE (EDEL_GUID = @GUID);

IF ( @Copy = 1 )
BEGIN

SET @Version ='0.00'
SET @Title = SUBSTRING ( '(COPY) ' + @Title, 1, 100 )
SET @LAYOUT_ID = SUBSTRING ( 'CPY_' + @LAYOUT_ID , 1 , 20 ) 

END

/** COPY THE FORM CVALUES IN TO THE FORM OBJECT.**/
Insert Into ED_ENTITY_LAYOUTS 
  ( EDEL_GUID 
  , EDE_LAYOUT_ID 
  , EDEL_STATE 
  , EDEL_TITLE 
  , EDEL_HTTP_REFERENCE 
  , EDEL_INSTRUCTIONS 
  , EDEL_DESCRIPTION 
  , EDEL_UPDATE_REASON 
  , EDEL_RECORD_CATEGORY 
  , EDEL_RECORD_PREFIX
  , EDEL_TYPE_ID 
  , EDEL_VERSION 
  , EDEL_JAVA_SCRIPT 
  , EDEL_HAS_CS_SCRIPT 
  , EDEL_LANGUAGE 
  , EDEL_CDASH_METADATA 
  , EDEL_READ_ACCESS_ROLES
  , EDEL_EDIT_ACCESS_ROLES
  , EDEL_RELATED_ENTITIES
  , EDEL_DEFAULT_PAGE_LAYOUT
  , EDEL_LINK_CONTENT_SETTING
  , EDEL_DISPLAY_ENTITIES
  , EDEL_DISPLAY_AUTHOR_DETAILS
  , EDEL_AUTHOR_ONLY_EDIT_ACCESS
  , EDEL_AUTHOR_ONLY_DRAFT_ACCESS
  , EDEL_UPDATED_BY_USER_ID 
  , EDEL_UPDATED_BY 
  , EDEL_UPDATED_DATE 
  , EDEL_DELETED  ) 
SELECT 
    @NewGuid
  , @LAYOUT_ID 
  , 'Form_Draft'
  , @Title 
  , EDEL_HTTP_REFERENCE 
  , EDEL_INSTRUCTIONS 
  , EDEL_DESCRIPTION 
  , EDEL_UPDATE_REASON 
  , EDEL_RECORD_CATEGORY 
  , EDEL_RECORD_PREFIX
  , EDEL_TYPE_ID 
  , EDEL_VERSION 
  , EDEL_JAVA_SCRIPT 
  , EDEL_HAS_CS_SCRIPT 
  , EDEL_LANGUAGE 
  , EDEL_CDASH_METADATA 
  , EDEL_READ_ACCESS_ROLES
  , EDEL_EDIT_ACCESS_ROLES
  , EDEL_RELATED_ENTITIES
  , EDEL_DEFAULT_PAGE_LAYOUT
  , EDEL_LINK_CONTENT_SETTING
  , EDEL_DISPLAY_ENTITIES
  , EDEL_DISPLAY_AUTHOR_DETAILS
  , EDEL_AUTHOR_ONLY_EDIT_ACCESS
  , EDEL_AUTHOR_ONLY_DRAFT_ACCESS
  , EDEL_UPDATED_BY_USER_ID 
  , EDEL_UPDATED_BY 
  , EDEL_UPDATED_DATE 
  , 0
FROM ED_ENTITY_LAYOUTS 
WHERE (EDEL_GUID = @GUID);


/** COPY THE FORM SECTION IN TO THE FORM OBJECT.**/
INSERT INTO ED_ENTITY_LAYOUT_SECTIONS 
 ( EDELS_GUID 
  ,EDEL_GUID 
  ,EDELS_NUMBER 
  ,EDELS_ORDER 
  ,EDELS_NAME 
  ,EDELS_INSTRUCTIONS 
  ,EDELS_FIELD_NAME 
  ,EDELS_FIELD_VALUE 
  ,EDELS_ON_MATCH_VISIBLE 
  ,EDELS_VISIBLE 
  ,EDELS_DEFAULT_DISPLAY_ROLES 
  ,EDELS_DEFAULT_EDIT_ROLES ) 
SELECT 
  newid()
  ,@NewGuid
  ,EDELS_NUMBER 
  ,EDELS_ORDER 
  ,EDELS_NAME 
  ,EDELS_INSTRUCTIONS 
  ,EDELS_FIELD_NAME 
  ,EDELS_FIELD_VALUE 
  ,EDELS_ON_MATCH_VISIBLE 
  ,EDELS_VISIBLE 
  ,EDELS_DEFAULT_DISPLAY_ROLES 
  ,EDELS_DEFAULT_EDIT_ROLES
FROM ED_ENTITY_LAYOUT_SECTIONS 
WHERE (EDEL_GUID = @GUID);

/** COPY THE FORM FIELDS INTO THE NEW FORM OBJECT.**/
INSERT INTO ED_ENTITY_LAYOUT_FIELDS 
 ( EDEL_GUID 
  , EDELF_GUID 
  , EDE_LAYOUT_ID 
  , EDELF_FIELD_ID 
  , EDELF_TYPE_ID 
  , EDELF_ORDER 
  , EDELF_TITLE 
  , EDELF_INSTRUCTIONS 
  , EDELF_HTTP_REFERENCE 
  , EDELF_SECTION_ID 
  , EDELF_OPTIONS 
  , EDELF_SUMMARY_FIELD 
  , EDELF_MANDATORY 
  , EDELF_AI_DATA_POINT 
  , EDELF_HIDDEN 
  , EDELF_ANALYTICS_DATA_POINT
  , EDELF_DEFAULT_VALUE 
  , EDELF_UNIT 
  , EDELF_UNIT_SCALING 
  , EDELF_VALIDATION_LOWER_LIMIT 
  , EDELF_VALIDATION_UPPER_LIMIT 
  , EDELF_ALERT_LOWER_LIMIT 
  , EDELF_ALERT_UPPER_LIMIT 
  , EDELF_NORMAL_LOWER_LIMIT 
  , EDELF_NORMAL_UPPER_LIMIT 
  , EDELF_FIELD_CATEGORY 
  , EDELF_ANALOGUE_LEGEND_START 
  , EDELF_ANALOGUE_LEGEND_FINISH 
  , EDELF_JAVA_SCRIPT 
  , EDELF_TABLE 
  , EDELF_INITIAL_OPTION_LIST 
  , EDELF_FIELD_LAYOUT 
  , EDELF_INITIAL_VERSION 
  , EDELF_DELETED  ) 
SELECT 
   @NewGuid
  , NEWID()
  , EDE_LAYOUT_ID
  , EDELF_FIELD_ID 
  , EDELF_TYPE_ID 
  , EDELF_ORDER 
  , EDELF_TITLE 
  , EDELF_INSTRUCTIONS 
  , EDELF_HTTP_REFERENCE 
  , EDELF_SECTION_ID 
  , EDELF_OPTIONS 
  , EDELF_SUMMARY_FIELD 
  , EDELF_MANDATORY 
  , EDELF_AI_DATA_POINT
  , EDELF_ANALYTICS_DATA_POINT
  , EDELF_HIDDEN 
  , EDELF_DEFAULT_VALUE 
  , EDELF_UNIT 
  , EDELF_UNIT_SCALING 
  , EDELF_VALIDATION_LOWER_LIMIT 
  , EDELF_VALIDATION_UPPER_LIMIT 
  , EDELF_ALERT_LOWER_LIMIT 
  , EDELF_ALERT_UPPER_LIMIT 
  , EDELF_NORMAL_LOWER_LIMIT 
  , EDELF_NORMAL_UPPER_LIMIT 
  , EDELF_FIELD_CATEGORY 
  , EDELF_ANALOGUE_LEGEND_START 
  , EDELF_ANALOGUE_LEGEND_FINISH 
  , EDELF_JAVA_SCRIPT 
  , EDELF_TABLE 
  , EDELF_INITIAL_OPTION_LIST 
  , EDELF_FIELD_LAYOUT 
  , EDELF_INITIAL_VERSION 
  ,0
  FROM   ED_ENTITY_LAYOUT_FIELDS 
WHERE (EDEL_GUID = @GUID) and (EDELF_DELETED = 0);

GO

/****** Object:  StoredProcedure dbo.USR_ENTITY_LAYOUT_DELETE    Script Date: 01/04/2021 10:32:51 ******/

CREATE   PROCEDURE dbo.USR_ENTITY_LAYOUT_DELETE 
 @GUID UniqueIdentifier ,
 @UPDATED_BY_USER_ID NVarChar (100),
 @UPDATED_BY  NVarChar(30),
 @UPDATED_DATE DateTime
AS

UPDATE ED_ENTITY_LAYOUTS 
SET 
  EDEL_UPDATED_BY_USER_ID = @UPDATED_BY_USER_ID,  
  EDEL_UPDATED_BY = @UPDATED_BY,  
  EDEL_UPDATED_DATE = @UPDATED_DATE, 
  EDEL_DELETED = -1 
WHERE 	EDEL_DELETED = 0 
	AND EDEL_GUID = @GUID ;

GO

/****** Object:  StoredProcedure dbo.USR_ENTITY_LAYOUT_UPDATE    Script Date: 01/04/2021 10:32:51 ******/

CREATE PROCEDURE dbo.USR_ENTITY_LAYOUT_UPDATE
 @GUID UniqueIdentifier,
 @LAYOUT_ID NVarChar(20),
 @STATE  NVarChar(20),
 @TITLE NVarChar(80),
 @HTTP_REFERENCE NVarChar(250),
 @INSTRUCTIONS NText,
 @DESCRIPTION NText,   
 @UPDATE_REASON  NVarChar(50),
 @RECORD_CATEGORY NVarChar(100),
 @RECORD_PREFIX NVarChar(5),
 @TYPE_ID VarChar(25),
 @VERSION Float,
 @JAVA_SCRIPT NText,   
 @HAS_CS_SCRIPT Bit,
 @LANGUAGE VarChar(5),
 @CDASH_METADATA NVarChar(250),
 @READ_ACCESS_ROLES NVarChar(250),
 @EDIT_ACCESS_ROLES NVarChar(250),
 @RELATED_ENTITIES NVARCHAR(250),
 @DEFAULT_PAGE_LAYOUT NVARCHAR(50),
 @LINK_CONTENT_SETTING NVARCHAR(50),
 @DISPLAY_ENTITIES BIT,
 @DISPLAY_AUTHOR_DETAILS BIT,
 @AUTHOR_ONLY_EDIT_ACCESS BIT,
 @AUTHOR_ONLY_DRAFT_ACCESS BIT,
 @UPDATED_BY_USER_ID NVarChar(100),
 @UPDATED_BY NVarChar(30),
 @UPDATED_DATE DateTime
AS
UPDATE ED_ENTITY_LAYOUTS 
SET 
  EDE_LAYOUT_ID = @LAYOUT_ID ,
  EDEL_STATE = @STATE  ,
  EDEL_TITLE = @TITLE ,
  EDEL_HTTP_REFERENCE = @HTTP_REFERENCE ,
  EDEL_INSTRUCTIONS = @INSTRUCTIONS ,
  EDEL_DESCRIPTION = @DESCRIPTION ,
  EDEL_UPDATE_REASON = @UPDATE_REASON  ,
  EDEL_RECORD_CATEGORY = @RECORD_CATEGORY,
  EDEL_RECORD_PREFIX = @RECORD_PREFIX,
  EDEL_TYPE_ID = @TYPE_ID ,
  EDEL_VERSION = @VERSION,
  EDEL_JAVA_SCRIPT = @JAVA_SCRIPT, 
  EDEL_HAS_CS_SCRIPT = @HAS_CS_SCRIPT,
  EDEL_LANGUAGE = @LANGUAGE,
  EDEL_CDASH_METADATA = @CDASH_METADATA,
  EDEL_READ_ACCESS_ROLES = @READ_ACCESS_ROLES,
  EDEL_EDIT_ACCESS_ROLES = @EDIT_ACCESS_ROLES,
  EDEL_RELATED_ENTITIES = @RELATED_ENTITIES,
  EDEL_DEFAULT_PAGE_LAYOUT = @DEFAULT_PAGE_LAYOUT,
  EDEL_LINK_CONTENT_SETTING = @LINK_CONTENT_SETTING,
  EDEL_DISPLAY_ENTITIES = @DISPLAY_ENTITIES,
  EDEL_DISPLAY_AUTHOR_DETAILS = @DISPLAY_AUTHOR_DETAILS,
  EDEL_AUTHOR_ONLY_EDIT_ACCESS = @AUTHOR_ONLY_EDIT_ACCESS,
  EDEL_AUTHOR_ONLY_DRAFT_ACCESS = @AUTHOR_ONLY_DRAFT_ACCESS,
  EDEL_UPDATED_BY_USER_ID = @UPDATED_BY_USER_ID,
  EDEL_UPDATED_BY = @UPDATED_BY,
  EDEL_UPDATED_DATE =@UPDATED_DATE
WHERE (EDEL_GUID = @GUID) ;


GO

/****** Object:  StoredProcedure dbo.USR_ENTITY_LAYOUT_UPDATE    Script Date: 01/04/2021 10:32:52 ******/

CREATE PROCEDURE dbo.USR_ENTITY_LAYOUT_WITHDRAWN
 @APPLICATION_ID NVarChar (10),
 @LAYOUT_ID NVarChar(20),
 @UPDATED_BY_USER_ID NVarChar (100),
 @UPDATED_BY  NVarChar(30),
 @UPDATED_DATE DateTime
AS
UPDATE ED_ENTITY_LAYOUTS 
SET 
  EDEL_STATE = 'Withdrawn', 
  EDEL_UPDATED_BY_USER_ID = @UPDATED_BY_USER_ID,
  EDEL_UPDATED_BY = @UPDATED_BY,
  EDEL_UPDATED_DATE =@UPDATED_DATE
WHERE (EDE_LAYOUT_ID = @LAYOUT_ID)
  AND (EDEL_STATE = 'Form_Issued' ) ;



GO




PRINT N'FINISH: 008_R1.0_ED_ENTITY_LAYOUTS_CREATE_STORED_PROCEDURES.'; 
GO
