/****** File: 009_R1.0_ED_ENTITY_LAYOUT_FIELDS_CREATE_PROCS.sql ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

DECLARE @RC int

EXECUTE @RC = dbo.usr_DB_Add_Database_Update 
   009, 'R1.0','ED_ENTITY_LAYOUT_FIELDS', 
   'CREATE STORED PROCEDURES.'

GO

PRINT N'START: 009_R1.0_ED_ENTITY_LAYOUT_FIELDS_CREATE_PROCS.'; 
GO
/****** Object:  StoredProcedure dbo.USR_ENTITY_LAYOUT_FIELD_ADD    Script Date: 01/04/2021 11:39:53 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.USR_ENTITY_LAYOUT_FIELD_ADD') AND type in (N'P', N'PC'))
DROP PROCEDURE dbo.USR_ENTITY_LAYOUT_FIELD_ADD
GO

/****** Object:  StoredProcedure dbo.USR_ENTITY_LAYOUT_FIELD_DELETE    Script Date: 01/04/2021 11:39:54 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.USR_ENTITY_LAYOUT_FIELD_DELETE') AND type in (N'P', N'PC'))
DROP PROCEDURE dbo.USR_ENTITY_LAYOUT_FIELD_DELETE
GO

/****** Object:  StoredProcedure dbo.USR_ENTITY_LAYOUT_FIELD_UPDATE    Script Date: 01/04/2021 11:39:54 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.USR_ENTITY_LAYOUT_FIELD_UPDATE') AND type in (N'P', N'PC'))
DROP PROCEDURE dbo.USR_ENTITY_LAYOUT_FIELD_UPDATE
GO

/****** Object:  View [dbo].[ED_ENTITY_LAYOUT_FIELD_VIEW]    Script Date: 01/06/2021 16:56:23 ******/
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ED_ENTITY_LAYOUT_FIELD_VIEW]'))
DROP VIEW [dbo].[ED_ENTITY_LAYOUT_FIELD_VIEW]
GO

/****** Object:  View [dbo].[ED_ENTITY_LAYOUT_FIELD_VIEW]    Script Date: 01/05/2021 11:30:49 ******/
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ED_ENTITY_FIELD_VIEW]'))
DROP VIEW [dbo].[ED_ENTITY_FIELD_VIEW]
GO

/****** Object:  View [dbo].[ED_ENTITY_LAYOUT_FIELD_VIEW]    Script Date: 01/05/2021 11:30:49 ******/

CREATE VIEW [dbo].[ED_ENTITY_FIELD_VIEW]
AS
SELECT dbo.ED_ENTITY_LAYOUTS.CU_GUID, 
  dbo.ED_ENTITY_LAYOUTS.EDEL_GUID,  
  dbo.ED_ENTITY_LAYOUTS.EDE_LAYOUT_ID, 
  dbo.ED_ENTITY_LAYOUTS.EDEL_STATE, 
  dbo.ED_ENTITY_LAYOUTS.EDEL_TITLE, 
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_GUID,  
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_FIELD_ID AS FIELD_ID, 
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_TYPE_ID, 
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_ORDER, 
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_TITLE, 
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_INSTRUCTIONS, 
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_HTTP_REFERENCE, 
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_SECTION_ID, 
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_OPTIONS, 
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_SUMMARY_FIELD, 
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_MANDATORY, 
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_AI_DATA_POINT, 
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_ANALYTICS_DATA_POINT, 
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_HIDDEN, 
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_EX_SELECTION_LIST_ID, 
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_EX_SELECTION_LIST_CATEGORY, 
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_DEFAULT_VALUE, 
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_UNIT, 
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_UNIT_SCALING, 
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_VALIDATION_LOWER_LIMIT, 
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_VALIDATION_UPPER_LIMIT, 
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_ALERT_LOWER_LIMIT, 
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_ALERT_UPPER_LIMIT, 
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_NORMAL_LOWER_LIMIT, 
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_NORMAL_UPPER_LIMIT, 
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_FIELD_CATEGORY, 
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_ANALOGUE_LEGEND_START, 
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_ANALOGUE_LEGEND_FINISH, 
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_JAVA_SCRIPT, 
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_TABLE, 
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_INITIAL_OPTION_LIST, 
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_FIELD_LAYOUT,
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_INITIAL_VERSION, 
  dbo.ED_ENTITY_LAYOUT_FIELDS.EDELF_DELETED
FROM  dbo.ED_ENTITY_LAYOUTS INNER JOIN
  dbo.ED_ENTITY_LAYOUT_FIELDS ON dbo.ED_ENTITY_LAYOUTS.EDEL_GUID = dbo.ED_ENTITY_LAYOUT_FIELDS.EDEL_GUID

GO


/****** Object:  StoredProcedure dbo.USR_ENTITY_LAYOUT_FIELD_ADD    Script Date: 01/04/2021 11:39:54 ******/

CREATE PROCEDURE dbo.USR_ENTITY_LAYOUT_FIELD_ADD
  @LAYOUT_GUID uniqueidentifier,
	@GUID uniqueidentifier  ,
	@LAYOUT_ID nvarchar(20) ,
	@FIELD_ID nvarchar(20)  ,
	@TYPE_ID varchar(30) ,
	@ORDER smallint ,
	@TITLE nvarchar(150) ,
	@INSTRUCTIONS ntext ,
	@HTTP_REFERENCE nvarchar(150) ,
	@SECTION_ID smallint ,
	@OPTIONS nvarchar(256) ,
	@SUMMARY_FIELD bit ,
	@MANDATORY bit ,
	@AI_DATA_POINT bit ,
	@ANALYTICS_DATA_POINT bit,
	@HIDDEN bit ,
  @EX_SELECTION_LIST_ID nvarchar(250),
  @EX_SELECTION_LIST_CATEGORY nvarchar(250),
	@DEFAULT_VALUE nvarchar(100) ,
	@UNIT nvarchar(15) ,
	@UNIT_SCALING nvarchar(15) ,
	@VALIDATION_LOWER_LIMIT float ,
	@VALIDATION_UPPER_LIMIT float ,
	@ALERT_LOWER_LIMIT float ,
	@ALERT_UPPER_LIMIT float ,
	@NORMAL_LOWER_LIMIT int ,
	@NORMAL_UPPER_LIMIT int ,
	@FIELD_CATEGORY varchar(50) ,
	@ANALOGUE_LEGEND_START varchar(30) ,
	@ANALOGUE_LEGEND_FINISH varchar(30) ,
	@JAVA_SCRIPT ntext ,
	@TABLE ntext ,
	@FIELD_LAYOUT NVARCHAR(50),
	@INITIAL_OPTION_LIST nvarchar(250) ,
	@INITIAL_VERSION smallint
AS

INSERT INTO ED_ENTITY_LAYOUT_FIELDS 
 ( EDEL_GUID
  ,EDELF_GUID
  ,EDE_LAYOUT_ID
  ,EDELF_FIELD_ID
  ,EDELF_TYPE_ID
  ,EDELF_ORDER
  ,EDELF_TITLE
  ,EDELF_INSTRUCTIONS
  ,EDELF_HTTP_REFERENCE
  ,EDELF_SECTION_ID
  ,EDELF_OPTIONS
  ,EDELF_SUMMARY_FIELD
  ,EDELF_MANDATORY
  ,EDELF_AI_DATA_POINT
  ,EDELF_ANALYTICS_DATA_POINT
  ,EDELF_HIDDEN
  ,EDELF_EX_SELECTION_LIST_ID
  ,EDELF_EX_SELECTION_LIST_CATEGORY
  ,EDELF_DEFAULT_VALUE
  ,EDELF_UNIT
  ,EDELF_UNIT_SCALING
  ,EDELF_VALIDATION_LOWER_LIMIT
  ,EDELF_VALIDATION_UPPER_LIMIT
  ,EDELF_ALERT_LOWER_LIMIT
  ,EDELF_ALERT_UPPER_LIMIT
  ,EDELF_NORMAL_LOWER_LIMIT
  ,EDELF_NORMAL_UPPER_LIMIT
  ,EDELF_FIELD_CATEGORY
  ,EDELF_ANALOGUE_LEGEND_START
  ,EDELF_ANALOGUE_LEGEND_FINISH
  ,EDELF_JAVA_SCRIPT
  ,EDELF_TABLE
  ,EDELF_INITIAL_OPTION_LIST
  ,EDELF_FIELD_LAYOUT
  ,EDELF_INITIAL_VERSION
  ,EDELF_DELETED ) 
VALUES 
 ( @LAYOUT_GUID
  ,@GUID
  ,@LAYOUT_ID
  ,@FIELD_ID
  ,@TYPE_ID
  ,@ORDER
  ,@TITLE
  ,@INSTRUCTIONS
  ,@HTTP_REFERENCE
  ,@SECTION_ID
  ,@OPTIONS
  ,@SUMMARY_FIELD
  ,@MANDATORY
  ,@AI_DATA_POINT
  ,@ANALYTICS_DATA_POINT
  ,@HIDDEN
  ,@EX_SELECTION_LIST_ID
  ,@EX_SELECTION_LIST_CATEGORY
  ,@DEFAULT_VALUE
  ,@UNIT
  ,@UNIT_SCALING
  ,@VALIDATION_LOWER_LIMIT
  ,@VALIDATION_UPPER_LIMIT
  ,@ALERT_LOWER_LIMIT
  ,@ALERT_UPPER_LIMIT
  ,@NORMAL_LOWER_LIMIT
  ,@NORMAL_UPPER_LIMIT
  ,@FIELD_CATEGORY
  ,@ANALOGUE_LEGEND_START
  ,@ANALOGUE_LEGEND_FINISH
  ,@JAVA_SCRIPT
  ,@TABLE
  ,@INITIAL_OPTION_LIST
  ,@FIELD_LAYOUT
  ,@INITIAL_VERSION
  ,0 );

GO

/****** Object:  StoredProcedure dbo.USR_ENTITY_LAYOUT_FIELD_DELETE    Script Date: 01/04/2021 11:39:54 ******/
CREATE   PROCEDURE dbo.USR_ENTITY_LAYOUT_FIELD_DELETE 
 @Guid UniqueIdentifier
AS

UPDATE ED_ENTITY_LAYOUT_FIELDS 
SET 
  EDELF_DELETED = -1 
WHERE 	EDELF_DELETED = 0 
	AND EDELF_GUID = @Guid ;
GO

/****** Object:  StoredProcedure dbo.USR_ENTITY_LAYOUT_FIELD_UPDATE    Script Date: 01/04/2021 11:39:54 ******/

CREATE PROCEDURE dbo.USR_ENTITY_LAYOUT_FIELD_UPDATE
  @LAYOUT_GUID uniqueidentifier,
	@GUID uniqueidentifier  ,
	@LAYOUT_ID nvarchar(20) ,
	@FIELD_ID nvarchar(20)  ,
	@TYPE_ID varchar(30) ,
	@ORDER smallint ,
	@TITLE nvarchar(150) ,
	@INSTRUCTIONS ntext ,
	@HTTP_REFERENCE nvarchar(150) ,
	@SECTION_ID smallint ,
	@OPTIONS nvarchar(256) ,
	@SUMMARY_FIELD bit ,
	@MANDATORY bit ,
	@AI_DATA_POINT bit ,
	@ANALYTICS_DATA_POINT bit,
	@HIDDEN bit ,
  @EX_SELECTION_LIST_ID nvarchar(250),
  @EX_SELECTION_LIST_CATEGORY nvarchar(250),
	@DEFAULT_VALUE nvarchar(100) ,
	@UNIT nvarchar(15) ,
	@UNIT_SCALING nvarchar(15) ,
	@VALIDATION_LOWER_LIMIT float ,
	@VALIDATION_UPPER_LIMIT float ,
	@ALERT_LOWER_LIMIT float ,
	@ALERT_UPPER_LIMIT float ,
	@NORMAL_LOWER_LIMIT int ,
	@NORMAL_UPPER_LIMIT int ,
	@FIELD_CATEGORY varchar(50) ,
	@ANALOGUE_LEGEND_START varchar(30) ,
	@ANALOGUE_LEGEND_FINISH varchar(30) ,
	@JAVA_SCRIPT ntext ,
	@TABLE ntext ,
	@FIELD_LAYOUT NVARCHAR(50),
	@INITIAL_OPTION_LIST nvarchar(250) ,
	@INITIAL_VERSION smallint
AS

UPDATE 	ED_ENTITY_LAYOUT_FIELDS 
SET	
   EDE_LAYOUT_ID = @LAYOUT_ID
  ,EDELF_FIELD_ID = @FIELD_ID
  ,EDELF_TYPE_ID = @TYPE_ID
  ,EDELF_ORDER = @ORDER
  ,EDELF_TITLE = @TITLE
  ,EDELF_INSTRUCTIONS = @INSTRUCTIONS
  ,EDELF_HTTP_REFERENCE = @HTTP_REFERENCE
  ,EDELF_SECTION_ID = @SECTION_ID
  ,EDELF_OPTIONS = @OPTIONS
  ,EDELF_SUMMARY_FIELD = @SUMMARY_FIELD
  ,EDELF_MANDATORY = @MANDATORY
  ,EDELF_AI_DATA_POINT = @AI_DATA_POINT
  ,EDELF_ANALYTICS_DATA_POINT = @ANALYTICS_DATA_POINT
  ,EDELF_HIDDEN = @HIDDEN
  ,EDELF_EX_SELECTION_LIST_ID = @EX_SELECTION_LIST_ID
  ,EDELF_EX_SELECTION_LIST_CATEGORY = @EX_SELECTION_LIST_CATEGORY
  ,EDELF_DEFAULT_VALUE = @DEFAULT_VALUE
  ,EDELF_UNIT = @UNIT
  ,EDELF_UNIT_SCALING = @UNIT_SCALING
  ,EDELF_VALIDATION_LOWER_LIMIT = @VALIDATION_LOWER_LIMIT
  ,EDELF_VALIDATION_UPPER_LIMIT = @VALIDATION_UPPER_LIMIT
  ,EDELF_ALERT_LOWER_LIMIT = @ALERT_LOWER_LIMIT
  ,EDELF_ALERT_UPPER_LIMIT = @ALERT_UPPER_LIMIT
  ,EDELF_NORMAL_LOWER_LIMIT = @NORMAL_LOWER_LIMIT
  ,EDELF_NORMAL_UPPER_LIMIT = @NORMAL_UPPER_LIMIT
  ,EDELF_FIELD_CATEGORY = @FIELD_CATEGORY
  ,EDELF_ANALOGUE_LEGEND_START = @ANALOGUE_LEGEND_START
  ,EDELF_ANALOGUE_LEGEND_FINISH = @ANALOGUE_LEGEND_FINISH
  ,EDELF_JAVA_SCRIPT = @JAVA_SCRIPT
  ,EDELF_TABLE = @TABLE
  ,EDELF_INITIAL_OPTION_LIST = @INITIAL_OPTION_LIST
  ,EDELF_FIELD_LAYOUT = @FIELD_LAYOUT
  ,EDELF_INITIAL_VERSION = @INITIAL_VERSION
FROM ED_ENTITY_LAYOUT_FIELDS 
WHERE  (EDELF_GUID = @GUID );

GO




PRINT N'FINISH: 009_R1.0_ED_ENTITY_LAYOUT_FIELDS_CREATE_PROCS.'; 
GO
