/****** File: 010_R1.0_ED_ENTITIES_CREATE_STORED_PROCEDURES.sql ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

DECLARE @RC int

EXECUTE @RC = dbo.usr_DB_Add_Database_Update 
   010, 'R1.0','ED_ENTITIES', 
   'CREATE STORED PROCEDURES.'
GO

PRINT N'START: 010_R1.0_ED_ENTITYs_CREATE_STORED_PROCEDURES.'; 
GO

/****** Object:  StoredProcedure [dbo].[USR_ENTITY_CREATE]    Script Date: 01/07/2021 11:18:08 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USR_ENTITY_CREATE]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[USR_ENTITY_CREATE]
GO

/****** Object:  StoredProcedure [dbo].[USR_ENTITY_DELETE]    Script Date: 01/07/2021 11:18:08 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USR_ENTITY_DELETE]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[USR_ENTITY_DELETE]
GO

/****** Object:  StoredProcedure [dbo].[USR_ENTITY_LOCK]    Script Date: 01/07/2021 11:20:00 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USR_ENTITY_LOCK]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[USR_ENTITY_LOCK]
GO

/****** Object:  StoredProcedure [dbo].[USR_ENTITY_UNLOCK]    Script Date: 01/07/2021 11:20:00 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USR_ENTITY_UNLOCK]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[USR_ENTITY_UNLOCK]
GO

/****** Object:  StoredProcedure [dbo].[USR_ENTITY_UPDATE]    Script Date: 01/07/2021 11:20:00 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USR_ENTITY_UPDATE]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[USR_ENTITY_UPDATE]
GO

/****** Object:  View [dbo].[ED_ENTITY_VIEW]    Script Date: 01/07/2021 12:35:38 ******/
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ED_ENTITY_VIEW]'))
DROP VIEW [dbo].[ED_ENTITY_VIEW]
GO


/****** Object:  View [dbo].[ED_ENTITY_FILTER_VIEW]    Script Date: 01/08/2021 10:58:14 ******/
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ED_ENTITY_FILTER_VIEW]'))
DROP VIEW [dbo].[ED_ENTITY_FILTER_VIEW]
GO

/****** Object:  View [dbo].[ED_ENTITY_VALUE_VIEW]    Script Date: 01/13/2021 16:52:50 ******/
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[ED_ENTITY_VALUE_VIEW]'))
DROP VIEW [dbo].[ED_ENTITY_VALUE_VIEW]
GO

/****** Object:  View [dbo].[ED_ENTITY_VIEW]    Script Date: 01/07/2021 12:35:38 ******/

CREATE VIEW [dbo].[ED_ENTITY_VIEW]
AS
SELECT 
  dbo.ED_ENTITIES.EDE_GUID, 
  dbo.ED_ENTITY_LAYOUTS.EDEL_GUID, 
  dbo.ED_ENTITY_LAYOUTS.EDE_LAYOUT_ID, 
  dbo.ED_ENTITY_LAYOUTS.EDEL_TITLE, 
  dbo.ED_ENTITIES.EDE_ENTITY_DATE,
  dbo.ED_ENTITIES.EDE_STATE, 
  dbo.ED_ENTITIES.EDE_ENTITY_ID, 
  dbo.ED_ENTITIES.EDE_SERIAL_ID, 
  dbo.ED_ENTITIES.EDE_SOURCE_ID, 
  dbo.ED_ENTITIES.EDE_PARENT_ORG_ID,
  dbo.ED_ENTITIES.EDE_AUTHOR_USER_ID,
  dbo.ED_ENTITIES.EDE_AUTHOR,
  dbo.ED_ENTITIES.EDE_PARENT_LAYOUT_ID,
  dbo.ED_ENTITIES.EDE_PARENT_GUID,
  dbo.ED_ENTITIES.EDE_ENTITY_ACCESS,
  dbo.ED_ENTITIES.EDE_COLLECTION_EVENT_ID,  
  dbo.ED_ENTITIES.EDE_AI_DATA_INDEX,  
  dbo.ED_ENTITIES.EDE_VISABILITY,
  dbo.ED_ENTITIES.EDE_SIGN_OFFS, 
  dbo.ED_ENTITIES.EDE_BOOKED_OUT_USER_ID, 
  dbo.ED_ENTITIES.EDE_BOOKED_OUT, 
  dbo.ED_ENTITIES.EDE_UPDATED_BY_USER_ID, 
  dbo.ED_ENTITIES.EDE_UPDATED_BY, 
  dbo.ED_ENTITIES.EDE_UPDATED_DATE, 
  dbo.ED_ENTITY_LAYOUTS.EDEL_HTTP_REFERENCE,
  dbo.ED_ENTITY_LAYOUTS.EDEL_INSTRUCTIONS,
  dbo.ED_ENTITY_LAYOUTS.EDEL_DESCRIPTION,
  dbo.ED_ENTITY_LAYOUTS.EDEL_UPDATE_REASON,
  dbo.ED_ENTITY_LAYOUTS.EDEL_RECORD_CATEGORY,
  dbo.ED_ENTITY_LAYOUTS.EDEL_TYPE_ID,
  dbo.ED_ENTITY_LAYOUTS.EDEL_VERSION,
  dbo.ED_ENTITY_LAYOUTS.EDEL_JAVA_SCRIPT,
  dbo.ED_ENTITY_LAYOUTS.EDEL_HAS_CS_SCRIPT,
  dbo.ED_ENTITY_LAYOUTS.EDEL_LANGUAGE,
  dbo.ED_ENTITY_LAYOUTS.EDEL_READ_ACCESS_ROLES,
  dbo.ED_ENTITY_LAYOUTS.EDEL_EDIT_ACCESS_ROLES,
  dbo.ED_ENTITY_LAYOUTS.EDEL_PARENT_TYPE,
  dbo.ED_ENTITY_LAYOUTS.EDEL_PARENT_ACCESS,
  dbo.ED_ENTITY_LAYOUTS.EDEL_PARENT_ENTITIES,
  dbo.ED_ENTITY_LAYOUTS.EDEL_DEFAULT_PAGE_LAYOUT,
  dbo.ED_ENTITY_LAYOUTS.EDEL_LINK_CONTENT_SETTING,
  dbo.ED_ENTITY_LAYOUTS.EDEL_DISPLAY_ENTITIES,
  dbo.ED_ENTITY_LAYOUTS.EDEL_DISPLAY_AUTHOR_DETAILS,
  dbo.ED_ENTITY_LAYOUTS.EDEL_ENTITY_PREFIX,
  dbo.ED_ENTITY_LAYOUTS.EDEL_HEADER_FORMAT,
  dbo.ED_ENTITY_LAYOUTS.EDEL_FOOTER_FORMAT,
  dbo.ED_ENTITY_LAYOUTS.EDEL_UPDATED_BY, 
  dbo.ED_ENTITY_LAYOUTS.EDEL_UPDATED_DATE, 
  dbo.ED_ENTITIES.EDE_DELETED
FROM   dbo.ED_ENTITY_LAYOUTS INNER JOIN
  dbo.ED_ENTITIES ON dbo.ED_ENTITY_LAYOUTS.EDEL_GUID = dbo.ED_ENTITIES.EDEL_GUID
  WHERE dbo.ED_ENTITIES.EDE_DELETED = 0

GO

/****** Object:  View [dbo].[ED_ENTITY_FILTER_VIEW]    Script Date: 01/08/2021 10:58:14 ******/
CREATE VIEW [dbo].[ED_ENTITY_FILTER_VIEW]
AS
SELECT     
  dbo.ED_ENTITY_LAYOUTS.EDEL_GUID, 
  dbo.ED_ENTITIES.EDE_GUID,  
  dbo.ED_ENTITY_LAYOUTS.EDEL_HTTP_REFERENCE,
  dbo.ED_ENTITY_LAYOUTS.EDEL_INSTRUCTIONS,
  dbo.ED_ENTITY_LAYOUTS.EDEL_DESCRIPTION,
  dbo.ED_ENTITY_LAYOUTS.EDEL_UPDATE_REASON,
  dbo.ED_ENTITY_LAYOUTS.EDEL_RECORD_CATEGORY,
  dbo.ED_ENTITY_LAYOUTS.EDEL_TYPE_ID,
  dbo.ED_ENTITY_LAYOUTS.EDEL_VERSION,
  dbo.ED_ENTITY_LAYOUTS.EDEL_JAVA_SCRIPT,
  dbo.ED_ENTITY_LAYOUTS.EDEL_HAS_CS_SCRIPT,
  dbo.ED_ENTITY_LAYOUTS.EDEL_LANGUAGE,
  dbo.ED_ENTITY_LAYOUTS.EDEL_READ_ACCESS_ROLES,
  dbo.ED_ENTITY_LAYOUTS.EDEL_EDIT_ACCESS_ROLES,
  dbo.ED_ENTITY_LAYOUTS.EDEL_PARENT_TYPE,
  dbo.ED_ENTITY_LAYOUTS.EDEL_PARENT_ACCESS,
  dbo.ED_ENTITY_LAYOUTS.EDEL_PARENT_ENTITIES,
  dbo.ED_ENTITY_LAYOUTS.EDEL_DEFAULT_PAGE_LAYOUT,
  dbo.ED_ENTITY_LAYOUTS.EDEL_LINK_CONTENT_SETTING,
  dbo.ED_ENTITY_LAYOUTS.EDEL_DISPLAY_ENTITIES,
  dbo.ED_ENTITY_LAYOUTS.EDEL_DISPLAY_AUTHOR_DETAILS,
  dbo.ED_ENTITY_LAYOUTS.EDEL_ENTITY_PREFIX,
  dbo.ED_ENTITY_LAYOUTS.EDEL_HEADER_FORMAT,
  dbo.ED_ENTITY_LAYOUTS.EDEL_FOOTER_FORMAT,
  dbo.ED_ENTITY_LAYOUTS.EDEL_UPDATED_BY, 
  dbo.ED_ENTITY_LAYOUTS.EDEL_UPDATED_DATE, 
  dbo.ED_ENTITIES.EDE_ENTITY_DATE,
  dbo.ED_ENTITIES.EDE_STATE, 
  dbo.ED_ENTITIES.EDE_ENTITY_ID, 
  dbo.ED_ENTITIES.EDE_SERIAL_ID, 
  dbo.ED_ENTITIES.EDE_SOURCE_ID, 
  dbo.ED_ENTITIES.EDE_PARENT_ORG_ID,
  dbo.ED_ENTITIES.EDE_AUTHOR_USER_ID,
  dbo.ED_ENTITIES.EDE_AUTHOR,
  dbo.ED_ENTITIES.EDE_PARENT_LAYOUT_ID,
  dbo.ED_ENTITIES.EDE_PARENT_GUID,
  dbo.ED_ENTITIES.EDE_ENTITY_ACCESS,
  dbo.ED_ENTITIES.EDE_COLLECTION_EVENT_ID,  
  dbo.ED_ENTITIES.EDE_AI_DATA_INDEX,  
  dbo.ED_ENTITIES.EDE_VISABILITY,
  dbo.ED_ENTITIES.EDE_SIGN_OFFS, 
  dbo.ED_ENTITIES.EDE_BOOKED_OUT_USER_ID, 
  dbo.ED_ENTITIES.EDE_BOOKED_OUT, 
  dbo.ED_ENTITIES.EDE_UPDATED_BY_USER_ID, 
  dbo.ED_ENTITIES.EDE_UPDATED_BY, 
  dbo.ED_ENTITIES.EDE_UPDATED_DATE, 
  dbo.ED_ENTITY_FIELDS.EDELF_FIELD_ID, 
  dbo.ED_ENTITY_FIELDS.EDELF_TYPE_ID, 
  dbo.ED_ENTITY_FIELDS.EDELF_TITLE, 
  dbo.ED_ENTITY_FIELDS.EDELF_OPTIONS, 
  dbo.ED_ENTITY_VALUES.EDEV_COLUMN_ID, 
  dbo.ED_ENTITY_VALUES.EDEV_ROW, 
  dbo.ED_ENTITY_VALUES.EDEV_STRING, 
  dbo.ED_ENTITY_VALUES.EDEV_NUMERIC, 
  dbo.ED_ENTITY_VALUES.EDEV_DATE, 
  dbo.ED_ENTITY_VALUES.EDEV_TEXT
FROM         dbo.ED_ENTITIES INNER JOIN
  dbo.ED_ENTITY_VALUES ON dbo.ED_ENTITIES.EDE_GUID = dbo.ED_ENTITY_VALUES.EDE_GUID INNER JOIN
  dbo.ED_ENTITY_FIELDS ON dbo.ED_ENTITY_VALUES.EDELF_GUID = dbo.ED_ENTITY_FIELDS.EDELF_GUID INNER JOIN
  dbo.ED_ENTITY_LAYOUTS ON dbo.ED_ENTITIES.EDEL_GUID = dbo.ED_ENTITY_LAYOUTS.EDEL_GUID
  WHERE dbo.ED_ENTITIES.EDE_DELETED = 0;

GO
/****** Object:  View [dbo].[ED_ENTITY_VALUE_VIEW]    Script Date: 01/13/2021 16:52:50 ******/

CREATE VIEW [dbo].[ED_ENTITY_VALUE_VIEW]
AS
SELECT   
  dbo.ED_ENTITY_FIELDS.EDEL_GUID, 
  dbo.ED_ENTITY_FIELDS.EDELF_GUID, 
  dbo.ED_ENTITY_FIELDS.EDE_LAYOUT_ID, 
  dbo.ED_ENTITY_FIELDS.EDELF_FIELD_ID AS FIELD_ID, 
  dbo.ED_ENTITY_FIELDS.EDELF_TYPE_ID, 
  dbo.ED_ENTITY_FIELDS.EDELF_ORDER, 
  dbo.ED_ENTITY_FIELDS.EDELF_TITLE, 
  dbo.ED_ENTITY_FIELDS.EDELF_INSTRUCTIONS, 
  dbo.ED_ENTITY_FIELDS.EDELF_HTTP_REFERENCE, 
  dbo.ED_ENTITY_FIELDS.EDELF_SECTION_ID, 
  dbo.ED_ENTITY_FIELDS.EDELF_OPTIONS, 
  dbo.ED_ENTITY_FIELDS.EDELF_SUMMARY_FIELD, 
  dbo.ED_ENTITY_FIELDS.EDELF_MANDATORY, 
  dbo.ED_ENTITY_FIELDS.EDELF_AI_DATA_POINT, 
  dbo.ED_ENTITY_FIELDS.EDELF_ANALYTICS_DATA_POINT, 
  dbo.ED_ENTITY_FIELDS.EDELF_HIDDEN, 
  dbo.ED_ENTITY_FIELDS.EDELF_EX_SELECTION_LIST_ID, 
  dbo.ED_ENTITY_FIELDS.EDELF_EX_SELECTION_LIST_CATEGORY, 
  dbo.ED_ENTITY_FIELDS.EDELF_DEFAULT_VALUE, 
  dbo.ED_ENTITY_FIELDS.EDELF_UNIT, 
  dbo.ED_ENTITY_FIELDS.EDELF_UNIT_SCALING, 
  dbo.ED_ENTITY_FIELDS.EDELF_VALIDATION_LOWER_LIMIT, 
  dbo.ED_ENTITY_FIELDS.EDELF_VALIDATION_UPPER_LIMIT, 
  dbo.ED_ENTITY_FIELDS.EDELF_ALERT_LOWER_LIMIT, 
  dbo.ED_ENTITY_FIELDS.EDELF_ALERT_UPPER_LIMIT, 
  dbo.ED_ENTITY_FIELDS.EDELF_NORMAL_LOWER_LIMIT, 
  dbo.ED_ENTITY_FIELDS.EDELF_NORMAL_UPPER_LIMIT, 
  dbo.ED_ENTITY_FIELDS.EDELF_FIELD_CATEGORY, 
  dbo.ED_ENTITY_FIELDS.EDELF_ANALOGUE_LEGEND_START, 
  dbo.ED_ENTITY_FIELDS.EDELF_ANALOGUE_LEGEND_FINISH, 
  dbo.ED_ENTITY_FIELDS.EDELF_JAVA_SCRIPT, 
  dbo.ED_ENTITY_FIELDS.EDELF_TABLE, 
  dbo.ED_ENTITY_FIELDS.EDELF_INITIAL_OPTION_LIST, 
  dbo.ED_ENTITY_FIELDS.EDELF_INITIAL_VERSION, 
  dbo.ED_ENTITY_VALUES.EDE_GUID,
  dbo.ED_ENTITY_VALUES.EDEV_GUID, 
  dbo.ED_ENTITY_VALUES.EDEV_COLUMN_ID, 
  dbo.ED_ENTITY_VALUES.EDEV_ROW, 
  dbo.ED_ENTITY_VALUES.EDEV_STRING, 
  dbo.ED_ENTITY_VALUES.EDEV_NUMERIC, 
  dbo.ED_ENTITY_VALUES.EDEV_DATE, 
  dbo.ED_ENTITY_VALUES.EDEV_TEXT
FROM         dbo.ED_ENTITY_VALUES INNER JOIN
                      dbo.ED_ENTITY_FIELDS ON dbo.ED_ENTITY_VALUES.EDELF_GUID = dbo.ED_ENTITY_FIELDS.EDELF_GUID

GO

/****** Object:  StoredProcedure [dbo].[USR_ENTITY_CREATE]    Script Date: 01/07/2021 11:18:08 ******/

CREATE  PROCEDURE [dbo].[USR_ENTITY_CREATE]
  @GUID uniqueidentifier,
	@LAYOUT_ID nvarchar(10),
  @PARENT_LAYOUT_ID nvarchar(10),
  @PARENT_GUID uniqueidentifier,
	@PARENT_ORG_ID nvarchar(10),
	@AUTHOR_USER_ID nvarchar(100),
	@AUTHOR nvarchar(100),
	@COLLECTION_EVENT_ID nvarchar(20),
	@UPDATED_BY_USER_ID nvarchar(100) ,
	@UPDATED_BY nvarchar(100) ,
	@UPDATED_DATE datetime 
AS

DECLARE @LAYOUT_GUID uniqueidentifier
DECLARE @ENTITY_ID nvarchar(20)
DECLARE @PREFIX nvarchar(5)
DECLARE @SERIAL_ID INT
DECLARE @NEW_SERIAL_ID INT

SELECT 	@LAYOUT_GUID = EDEL_GUID, @PREFIX = EDEL_ENTITY_PREFIX  
FROM ED_ENTITY_LAYOUT_ISSUED 
WHERE (EDE_LAYOUT_ID = @LAYOUT_ID);

IF (@PREFIX ='' )
BEGIN
 SELECT @PREFIX = 'REC_';
END 

SET @UPDATED_DATE = GetDate();

SELECT 	@NEW_SERIAL_ID = 1;

SELECT 	@SERIAL_ID = Max(EDE_SERIAL_ID) 
FROM 	ED_ENTITY_VIEW 
WHERE (EDE_LAYOUT_ID = @LAYOUT_ID) ;

IF (@SERIAL_ID > 0 )
BEGIN
 SELECT @NEW_SERIAL_ID = @SERIAL_ID + 1;
END 

SELECT @ENTITY_ID = @PREFIX + RIGHT( '00000000' + CONVERT(VARCHAR(8), @NEW_SERIAL_ID), 8 );

Insert Into ED_ENTITIES 
 ( EDE_GUID
  ,EDEL_GUID
  ,EDE_ENTITY_ID
  ,EDE_PARENT_ORG_ID
  ,EDE_AUTHOR_USER_ID
  ,EDE_AUTHOR
  ,EDE_PARENT_LAYOUT_ID
  ,EDE_PARENT_GUID
  ,EDE_STATE
  ,EDE_SERIAL_ID
  ,EDE_UPDATED_BY_USER_ID
  ,EDE_UPDATED_BY
  ,EDE_UPDATED_DATE
  ,EDE_DELETED ) 
values 
 (@GUID, 
  @LAYOUT_GUID, 
  @ENTITY_ID, 
  @PARENT_ORG_ID,
  @UPDATED_BY_USER_ID,
  @UPDATED_BY,
  @PARENT_LAYOUT_ID,
  @PARENT_GUID,
  'Empty_Record', 
  @NEW_SERIAL_ID, 
  @UPDATED_BY_USER_ID,
	@UPDATED_BY,
	@UPDATED_DATE,
  0);

GO

/****** Object:  StoredProcedure [dbo].[USR_ENTITY_DELETE]    Script Date: 01/07/2021 11:18:08 ******/

CREATE	PROCEDURE [dbo].[USR_ENTITY_DELETE]
  @GUID uniqueidentifier  ,
  @UPDATED_BY_USER_ID nvarchar(100) ,
	@UPDATED_BY nvarchar(100) ,
	@UPDATED_DATE datetime 
AS

UPDATE 	ED_ENTITIES 
SET 	
  EDE_UPDATED_BY_USER_ID =  @UPDATED_BY_USER_ID,  
  EDE_UPDATED_BY =  @UPDATED_BY,  
	EDE_UPDATED_DATE = @UPDATED_DATE , 
	EDE_DELETED = 1 
WHERE (EDE_DELETED = 0) 
  AND (EDE_GUID = @Guid) ;




GO


/****** Object:  StoredProcedure [dbo].[USR_ENTITY_LOCK]    Script Date: 01/07/2021 11:20:00 ******/

CREATE      PROCEDURE [dbo].[USR_ENTITY_LOCK]
  @GUID uniqueidentifier  ,
  @UPDATED_BY_USER_ID nvarchar(100) ,
	@UPDATED_BY nvarchar(100) ,
	@UPDATED_DATE datetime 
AS

UPDATE	ED_ENTITIES 
SET 	
  EDE_BOOKED_OUT_USER_ID = @UPDATED_BY_USER_ID,  
  EDE_BOOKED_OUT = @UPDATED_BY,  
  EDE_UPDATED_BY_USER_ID =  @UPDATED_BY_USER_ID,  
  EDE_UPDATED_BY =  @UPDATED_BY,  
	EDE_UPDATED_DATE = @UPDATED_DATE 
WHERE	(EDE_GUID = @GUID) 
  AND (EDE_BOOKED_OUT = '');




GO

/****** Object:  StoredProcedure [dbo].[USR_ENTITY_UNLOCK]    Script Date: 01/07/2021 11:20:00 ******/

CREATE PROCEDURE [dbo].[USR_ENTITY_UNLOCK]
  @GUID uniqueidentifier  ,
  @UPDATED_BY_USER_ID nvarchar(100) ,
	@UPDATED_BY nvarchar(100) ,
	@UPDATED_DATE datetime 
AS

UPDATE	ED_ENTITIES 
SET 	  
  EDE_BOOKED_OUT_USER_ID = '',  
  EDE_BOOKED_OUT = '',  
  EDE_UPDATED_BY_USER_ID =  @UPDATED_BY_USER_ID,  
  EDE_UPDATED_BY =  @UPDATED_BY,  
	EDE_UPDATED_DATE = @UPDATED_DATE 
WHERE	(EDE_GUID = @GUID) ;




GO

/****** Object:  StoredProcedure [dbo].[USR_ENTITY_UPDATE]    Script Date: 01/07/2021 11:20:00 ******/

CREATE PROCEDURE [dbo].[USR_ENTITY_UPDATE]
  @GUID uniqueidentifier,
	@STATE varchar(30),
	@SOURCE_ID nvarchar(20),
	@ENTITY_DATE datetime,
	@VISABILITY nvarchar(30),
	@ENTITY_ACCESS nvarchar(1000),
	@AI_DATA_INDEX nvarchar(1000),
	@SIGN_OFFS ntext,
	@UPDATED_BY_USER_ID nvarchar(100),
	@UPDATED_BY nvarchar(100),
	@UPDATED_DATE datetime 
AS

UPDATE 	ED_ENTITIES 
SET
   EDE_STATE = @STATE
  ,EDE_SOURCE_ID = @SOURCE_ID
  ,EDE_ENTITY_DATE = @ENTITY_DATE
  ,EDE_VISABILITY = @VISABILITY
  ,EDE_ENTITY_ACCESS = @ENTITY_ACCESS
  ,EDE_AI_DATA_INDEX = @AI_DATA_INDEX
  ,EDE_SIGN_OFFS = @SIGN_OFFS
  ,EDE_BOOKED_OUT_USER_ID = ''
  ,EDE_BOOKED_OUT = ''
  ,EDE_UPDATED_BY_USER_ID = @UPDATED_BY_USER_ID
  ,EDE_UPDATED_BY = @UPDATED_BY
  ,EDE_UPDATED_DATE = @UPDATED_DATE
WHERE 	(EDE_GUID = @GUID);

GO

PRINT N'FINISH: 010_R1.0_ED_ENTITYs_CREATE_STORED_PROCEDURES.'; 
GO
