/****** File: 011_R1.0_ED_EXT_SELECTION_lIST_CREATE_TBL_PROCS.sql ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

DECLARE @RC int

EXECUTE @RC = dbo.usr_DB_Add_Database_Update 
   010, 'R1.0','ED_SELECTION_LISTS', 
   'CREATE STORED PROCEDURES.'
GO

PRINT N'START: 011_R1.0_ED_EXT_SELECTION_lIST_CREATE_TBL_PROCS.'; 
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_XCL_Version]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[EvFormFieldSelectionList] DROP CONSTRAINT [DF_XCL_Version]
END

GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_XCL_Superseded]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[EvFormFieldSelectionList] DROP CONSTRAINT [DF_XCL_Superseded]
END

GO

/****** Object:  Table [dbo].[EvFormFieldSelectionList]    Script Date: 03/02/2021 12:06:38 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EvFormFieldSelectionList]') AND type in (N'U'))
DROP TABLE [dbo].[EvFormFieldSelectionList]
GO


/****** Object:  Table [dbo].[ED_RECORD_LAYOUTS]    Script Date: 12/24/2020 10:45:30 ******/

IF NOT EXISTS( SELECT 1 FROM sys.columns 
          WHERE Name = N'EDSL_GUID'
          AND Object_ID = Object_ID(N'ED_SELECTION_LISTS' ))
BEGIN

CREATE TABLE [dbo].[ED_SELECTION_LISTS](
	EDSL_GUID uniqueidentifier NOT NULL,
	EDSL_LIST_ID nvarchar(20) NULL,
	EDSL_STATE varchar(50) NULL,
	EDSL_TITLE nvarchar(100) NULL,
	EDSL_DESCRIPTION NText NULL,
	EDSL_JSON_LIST NText NULL,
	EDSL_VERSION int NULL,
	EDSL_UPDATED_BY_USER_ID nvarchar(100) NULL,
	EDSL_UPDATED_BY nvarchar(100) NULL,
	EDSL_UPDATED_DATE datetime NULL,
	EDSL_DELETED bit NULL,
 CONSTRAINT [PK_SELECTION_LISTS] PRIMARY KEY CLUSTERED 
(
	[EDSL_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

END
GO

/****** Object:  StoredProcedure dbo.USR_SELECTION_LIST_ADD    Script Date: 01/04/2021 10:32:51 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.USR_SELECTION_LIST_ADD') AND type in (N'P', N'PC'))
DROP PROCEDURE dbo.USR_SELECTION_LIST_ADD
GO

/****** Object:  StoredProcedure dbo.USR_SELECTION_LIST_DELETE    Script Date: 01/04/2021 10:32:51 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.USR_SELECTION_LIST_DELETE') AND type in (N'P', N'PC'))
DROP PROCEDURE dbo.USR_SELECTION_LIST_DELETE
GO

/****** Object:  StoredProcedure dbo.USR_SELECTION_LIST_UPDATE    Script Date: 01/04/2021 10:32:51 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.USR_SELECTION_LIST_UPDATE') AND type in (N'P', N'PC'))
DROP PROCEDURE dbo.USR_SELECTION_LIST_UPDATE
GO

/****** Object:  StoredProcedure dbo.USR_SELECTION_LIST_WITHDRAWN    Script Date: 01/04/2021 10:32:51 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.USR_SELECTION_LIST_WITHDRAWN') AND type in (N'P', N'PC'))
DROP PROCEDURE dbo.USR_SELECTION_LIST_WITHDRAWN
GO


/****** Object:  StoredProcedure dbo.USR_SELECTION_LIST_ADD    Script Date: 01/04/2021 10:32:51 ******/
CREATE PROCEDURE dbo.USR_SELECTION_LIST_ADD
 @GUID UniqueIdentifier,
 @LIST_ID NVarChar(20),
 @STATE  NVarChar(20),
 @TITLE NVarChar(80),
 @DESCRIPTION NText,
 @JSON_LIST NText,   
 @VERSION INT,
 @UPDATED_BY_USER_ID NVarChar(100),
 @UPDATED_BY NVarChar(30),
 @UPDATED_DATE DateTime
AS

Insert Into ED_SELECTION_LISTS 
  (EDSL_GUID
  ,EDSL_LIST_ID
  ,EDSL_STATE
  ,EDSL_TITLE
  ,EDSL_DESCRIPTION
  ,EDSL_JSON_LIST
  ,EDSL_VERSION
  ,EDSL_UPDATED_BY_USER_ID
  ,EDSL_UPDATED_BY
  ,EDSL_UPDATED_DATE
  ,EDSL_DELETED  ) 
values 
 ( @GUID
  ,@LIST_ID
  ,@STATE
  ,@TITLE
  ,@DESCRIPTION
  ,@JSON_LIST
  ,@VERSION
  ,@UPDATED_BY_USER_ID
  ,@UPDATED_BY
  ,@UPDATED_DATE,0  );

GO


/****** Object:  StoredProcedure dbo.USR_SELECTION_LIST_DELETE    Script Date: 01/04/2021 10:32:51 ******/

CREATE   PROCEDURE dbo.USR_SELECTION_LIST_DELETE 
 @GUID UniqueIdentifier ,
 @UPDATED_BY_USER_ID NVarChar (100),
 @UPDATED_BY  NVarChar(30),
 @UPDATED_DATE DateTime
AS

UPDATE ED_SELECTION_LISTS 
SET 
  EDSL_UPDATED_BY_USER_ID = @UPDATED_BY_USER_ID,  
  EDSL_UPDATED_BY = @UPDATED_BY,  
  EDSL_UPDATED_DATE = @UPDATED_DATE, 
  EDSL_DELETED = -1 
WHERE 	EDSL_DELETED = 0 
	AND EDSL_GUID = @GUID ;

GO

/****** Object:  StoredProcedure dbo.USR_SELECTION_LIST_UPDATE    Script Date: 01/04/2021 10:32:51 ******/

CREATE PROCEDURE dbo.USR_SELECTION_LIST_UPDATE
 @GUID UniqueIdentifier,
 @LIST_ID NVarChar(20),
 @STATE  NVarChar(20),
 @TITLE NVarChar(80),
 @DESCRIPTION NText,
 @JSON_LIST NText,      
 @VERSION INT,
 @UPDATED_BY_USER_ID NVarChar(100),
 @UPDATED_BY NVarChar(30),
 @UPDATED_DATE DateTime
AS
UPDATE ED_SELECTION_LISTS 
SET 
  EDSL_LIST_ID = @LIST_ID ,
  EDSL_STATE = @STATE  ,
  EDSL_TITLE = @TITLE ,
  EDSL_DESCRIPTION = @DESCRIPTION ,
  EDSL_JSON_LIST = @JSON_LIST, 
  EDSL_VERSION = @VERSION,
  EDSL_UPDATED_BY_USER_ID = @UPDATED_BY_USER_ID,
  EDSL_UPDATED_BY = @UPDATED_BY,
  EDSL_UPDATED_DATE = @UPDATED_DATE
WHERE (EDSL_GUID = @GUID) ;


GO

/****** Object:  StoredProcedure dbo.USR_SELECTION_LIST_UPDATE    Script Date: 01/04/2021 10:32:52 ******/

CREATE PROCEDURE dbo.USR_SELECTION_LIST_WITHDRAWN
 @LIST_ID NVarChar(20),
 @UPDATED_BY_USER_ID NVarChar (100),
 @UPDATED_BY  NVarChar(30),
 @UPDATED_DATE DateTime
AS
UPDATE ED_SELECTION_LISTS 
SET 
  EDSL_STATE = 'Withdrawn', 
  EDSL_UPDATED_BY_USER_ID = @UPDATED_BY_USER_ID,
  EDSL_UPDATED_BY = @UPDATED_BY,
  EDSL_UPDATED_DATE =@UPDATED_DATE
WHERE (EDSL_LIST_ID = @LIST_ID)
  AND (EDSL_STATE = 'Form_Issued' ) ;



GO



PRINT N'FINISH: 011_R1.0_ED_EXT_SELECTION_lIST_CREATE_TBL_PROCS.'; 
GO
