/****** File: 013_R1.0_ED_PAGE_LAYOUTS_CREATE_TBL_PROCS.sql ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

DECLARE @RC int

EXECUTE @RC = dbo.usr_DB_Add_Database_Update 
   013, 'R1.0','ED_PAGE_LAYOUTS', 
   'CREATE STORED PROCEDURES.'
GO

PRINT N'START: 013_R1.0_ED_PAGE_LAYOUTS_CREATE_TBL_PROCS.'; 
GO

/****** Object:  Table [dbo].[ED_RECORD_LAYOUTS]    Script Date: 12/24/2020 10:45:30 ******/

IF NOT EXISTS( SELECT 1 FROM sys.columns 
          WHERE Name = N'EDPL_GUID'
          AND Object_ID = Object_ID(N'ED_PAGE_LAYOUTS' ))
BEGIN

CREATE TABLE [dbo].[ED_PAGE_LAYOUTS](
	EDPL_GUID uniqueidentifier NOT NULL,
	EDPL_PAGE_ID nvarchar(10) NULL,
	EDPL_STATE varchar(30) NULL,
	UP_TYPE varchar(20) NULL,
	EDPL_HOME_PAGE BIT NULL,
	
	EDPL_TITLE nvarchar(100) NULL,
	EDPL_MENU_LOCATION varchar(30) NULL,
	EDPL_PAGE_COMMANDS nvarchar(250) NULL,	
	EDPL_HEADER_CONTENT NText NULL,
	EDPL_HEADER_GROUP_LIST nvarchar(250) NULL,
	
	EDPL_LEFT_CONTENT NText NULL,
	EDPL_LEFT_GROUP_LIST nvarchar(250) NULL,
	EDPL_LEFT_COLUMN_WIDTH SMALLINT NULL,
	
	EDPL_CENTER_CONTENT NText NULL,
	EDPL_CENTER_GROUP_LIST nvarchar(250) NULL,
	
	EDPL_RIGHT_CONTENT NText NULL,
	EDPL_RIGHT_GROUP_LIST nvarchar(250) NULL,
	EDPL_RIGHT_COLUMN_WIDTH SMALLINT NULL,
	
	EDPL_VERSION int NULL,
	EDPL_UPDATED_BY_USER_ID nvarchar(100) NULL,
	EDPL_UPDATED_BY nvarchar(100) NULL,
	EDPL_UPDATED_DATE datetime NULL,
	EDPL_DELETED bit NULL,
 CONSTRAINT [PK_PAGE_LAYOUTS] PRIMARY KEY CLUSTERED 
(
	[EDPL_GUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

END
GO

/****** Object:  StoredProcedure dbo.USR_PAGE_LAYOUT_ADD    Script Date: 01/04/2021 10:32:51 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.USR_PAGE_LAYOUT_ADD') AND type in (N'P', N'PC'))
DROP PROCEDURE dbo.USR_PAGE_LAYOUT_ADD
GO

/****** Object:  StoredProcedure dbo.USR_PAGE_LAYOUT_DELETE    Script Date: 01/04/2021 10:32:51 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.USR_PAGE_LAYOUT_DELETE') AND type in (N'P', N'PC'))
DROP PROCEDURE dbo.USR_PAGE_LAYOUT_DELETE
GO

/****** Object:  StoredProcedure dbo.USR_PAGE_LAYOUT_UPDATE    Script Date: 01/04/2021 10:32:51 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.USR_PAGE_LAYOUT_UPDATE') AND type in (N'P', N'PC'))
DROP PROCEDURE dbo.USR_PAGE_LAYOUT_UPDATE
GO

/****** Object:  StoredProcedure dbo.USR_PAGE_LAYOUT_WITHDRAWN    Script Date: 01/04/2021 10:32:51 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.USR_PAGE_LAYOUT_WITHDRAWN') AND type in (N'P', N'PC'))
DROP PROCEDURE dbo.USR_PAGE_LAYOUT_WITHDRAWN
GO


/****** Object:  StoredProcedure dbo.USR_PAGE_LAYOUT_ADD    Script Date: 01/04/2021 10:32:51 ******/
CREATE PROCEDURE dbo.USR_PAGE_LAYOUT_ADD
 @GUID UniqueIdentifier,
 @PAGE_ID NVarChar(10),
 @STATE  NVarChar(30),
 @USER_TYPE  NVarChar(20),
 @HOME_PAGE BIT,
 
 @TITLE NVarChar(100),
 @MENU_LOCATION varchar(30),
 @PAGE_COMMANDS nvarchar(250),
 @HEADER_CONTENT NText,
 @HEADER_GROUP_LIST nvarchar(250),   
 
 @LEFT_CONTENT NText,
 @LEFT_GROUP_LIST nvarchar(250),
 @LEFT_COLUMN_WIDTH SMALLINT,
 
 @CENTER_CONTENT NText,
 @CENTER_GROUP_LIST nvarchar(250),
 
 @RIGHT_CONTENT NText,
 @RIGHT_GROUP_LIST nvarchar(250),
 @RIGHT_COLUMN_WIDTH SMALLINT,
 
 @VERSION INT,
 @UPDATED_BY_USER_ID NVarChar(100),
 @UPDATED_BY NVarChar(30),
 @UPDATED_DATE DateTime
AS

Insert Into ED_PAGE_LAYOUTS 
  (EDPL_GUID,
   EDPL_PAGE_ID,
   EDPL_STATE,
   UP_TYPE,
   EDPL_HOME_PAGE,
   EDPL_TITLE,
   EDPL_MENU_LOCATION,
   EDPL_PAGE_COMMANDS,
   EDPL_HEADER_CONTENT,
   EDPL_HEADER_GROUP_LIST,
   EDPL_LEFT_CONTENT,
   EDPL_LEFT_GROUP_LIST,
   EDPL_LEFT_COLUMN_WIDTH, 
   EDPL_CENTER_CONTENT,
   EDPL_CENTER_GROUP_LIST,
   EDPL_RIGHT_CONTENT ,
   EDPL_RIGHT_GROUP_LIST ,
   EDPL_RIGHT_COLUMN_WIDTH,
   EDPL_VERSION,
   EDPL_UPDATED_BY_USER_ID,
   EDPL_UPDATED_BY,
   EDPL_UPDATED_DATE,
   EDPL_DELETED  ) 
values 
 (@GUID,
  @PAGE_ID,
  @STATE,
  @USER_TYPE,
  @HOME_PAGE,
  @TITLE,
  @MENU_LOCATION,
  @PAGE_COMMANDS,
  @HEADER_CONTENT,
  @HEADER_GROUP_LIST,
  @LEFT_CONTENT,
  @LEFT_GROUP_LIST,
  @LEFT_COLUMN_WIDTH, 
  @CENTER_CONTENT,
  @CENTER_GROUP_LIST,
  @RIGHT_CONTENT ,
  @RIGHT_GROUP_LIST ,
  @RIGHT_COLUMN_WIDTH,
  @VERSION,
  @UPDATED_BY_USER_ID,
  @UPDATED_BY,
  @UPDATED_DATE,0  );

GO


/****** Object:  StoredProcedure dbo.USR_PAGE_LAYOUT_DELETE    Script Date: 01/04/2021 10:32:51 ******/

CREATE   PROCEDURE dbo.USR_PAGE_LAYOUT_DELETE 
 @GUID UniqueIdentifier ,
 @UPDATED_BY_USER_ID NVarChar (100),
 @UPDATED_BY  NVarChar(30),
 @UPDATED_DATE DateTime
AS

UPDATE ED_PAGE_LAYOUTS 
SET 
  EDPL_UPDATED_BY_USER_ID = @UPDATED_BY_USER_ID,  
  EDPL_UPDATED_BY = @UPDATED_BY,  
  EDPL_UPDATED_DATE = @UPDATED_DATE, 
  EDPL_DELETED = -1 
WHERE 	EDPL_DELETED = 0 
	AND EDPL_GUID = @GUID ;

GO

/****** Object:  StoredProcedure dbo.USR_PAGE_LAYOUT_UPDATE    Script Date: 01/04/2021 10:32:51 ******/

CREATE PROCEDURE dbo.USR_PAGE_LAYOUT_UPDATE
 @GUID UniqueIdentifier,
 @PAGE_ID NVarChar(10),
 @STATE  NVarChar(30),
 @USER_TYPE  NVarChar(20),
 @HOME_PAGE BIT,
 
 @TITLE NVarChar(100),
 @MENU_LOCATION varchar(30),
 @PAGE_COMMANDS nvarchar(250),
 @HEADER_CONTENT NText,
 @HEADER_GROUP_LIST nvarchar(250),  
 
 @LEFT_CONTENT NText,
 @LEFT_GROUP_LIST nvarchar(250),
 @LEFT_COLUMN_WIDTH SMALLINT,
 
 @CENTER_CONTENT NText,
 @CENTER_GROUP_LIST nvarchar(250),
 
 @RIGHT_CONTENT NText,
 @RIGHT_GROUP_LIST nvarchar(250),
 @RIGHT_COLUMN_WIDTH SMALLINT,
 
 @VERSION INT,
 @UPDATED_BY_USER_ID NVarChar(100),
 @UPDATED_BY NVarChar(30),
 @UPDATED_DATE DateTime
AS
UPDATE ED_PAGE_LAYOUTS 
SET 
  EDPL_PAGE_ID = @PAGE_ID,
  EDPL_STATE = @STATE,
  UP_TYPE = @USER_TYPE,
  EDPL_HOME_PAGE = @HOME_PAGE,
  EDPL_TITLE = @TITLE,
  EDPL_MENU_LOCATION = @MENU_LOCATION,
  EDPL_PAGE_COMMANDS = @PAGE_COMMANDS,
  
  EDPL_HEADER_CONTENT = @HEADER_CONTENT ,
  EDPL_HEADER_GROUP_LIST = @HEADER_GROUP_LIST, 
  
  EDPL_LEFT_CONTENT= @LEFT_CONTENT, 
  EDPL_LEFT_GROUP_LIST = @LEFT_GROUP_LIST, 
  EDPL_LEFT_COLUMN_WIDTH = @LEFT_COLUMN_WIDTH, 
  
  EDPL_CENTER_CONTENT = @CENTER_CONTENT, 
  EDPL_CENTER_GROUP_LIST = @CENTER_GROUP_LIST, 
  
  EDPL_RIGHT_CONTENT = @RIGHT_CONTENT, 
  EDPL_RIGHT_GROUP_LIST = @RIGHT_GROUP_LIST, 
  EDPL_RIGHT_COLUMN_WIDTH = @RIGHT_COLUMN_WIDTH, 
  
  EDPL_VERSION = @VERSION,
  EDPL_UPDATED_BY_USER_ID = @UPDATED_BY_USER_ID,
  EDPL_UPDATED_BY = @UPDATED_BY,
  EDPL_UPDATED_DATE = @UPDATED_DATE
WHERE (EDPL_GUID = @GUID) ;


GO

/****** Object:  StoredProcedure dbo.USR_PAGE_LAYOUT_UPDATE    Script Date: 01/04/2021 10:32:52 ******/

CREATE PROCEDURE dbo.USR_PAGE_LAYOUT_WITHDRAWN
 @PAGE_ID NVarChar(20),
 @UPDATED_BY_USER_ID NVarChar (100),
 @UPDATED_BY  NVarChar(30),
 @UPDATED_DATE DateTime
AS
UPDATE ED_PAGE_LAYOUTS 
SET 
  UP_TYPE = 'Withdrawn', 
  EDPL_UPDATED_BY_USER_ID = @UPDATED_BY_USER_ID,
  EDPL_UPDATED_BY = @UPDATED_BY,
  EDPL_UPDATED_DATE =@UPDATED_DATE
WHERE (EDPL_PAGE_ID = @PAGE_ID)
  AND (UP_TYPE = 'Form_Issued' ) ;



GO



PRINT N'FINISH: 013_R1.0_ED_PAGE_LAYOUTS_CREATE_TBL_PROCS.'; 
GO
