<?xml version="1.0" encoding="ISO-8859-1" ?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"  >
  <!--
*******************************************************************************
*                COPYRIGHT (C) EVADO HOLDING Pty. Ltd.  2000 - 2016
*
*                            ALL RIGHTS RESERVED
*
*******************************************************************************
-->
  <!-- Includes 
  -->
  <xsl:include href="./crf_trial.xsl" />

  <xsl:variable name="textboxsize" select="10" />
  <xsl:variable name="ResponseColumn" select="33" />
  <xsl:output method="html" omit-xml-declaration="yes" indent="yes" encoding="ISO-8859-1" />
  <!--
  
    ====================== CLINICAL REPORT FORM - HeadER SECTION ================= 
     
  -->
  <xsl:template match="EvCaseReportForm">
    <h1 align="Center" >Case Report Form</h1>
    
    <xsl:apply-templates />

    <p align="Center">
      Case Report Form generated by <xsl:value-of select="ReportCreatedBy" />on <xsl:value-of select="stReportCreated" />.
    </p>

  </xsl:template>
  <!--  

 ============================   Call Trial Template   =========================
-->

  <xsl:template match="EvCaseReportForm/Trial">
    <xsl:call-template name="Trial"></xsl:call-template>
  </xsl:template>

  <!--  

 ============================   Call Subject Template   =========================
-->

  <xsl:template match="EvCaseReportForm/Subject">

    <div class="Page_Break_Before">
    </div>
    <h2 class="Left" style="margin-left:10px">Trial Subject:</h2>
    <xsl:call-template name="Subject">
    </xsl:call-template>

  </xsl:template>

  <!--  

 ============================   Call Medications Template   =========================
 
-->
  <!--
 -->
  <xsl:template match="EvCaseReportForm/ConcomitantMedications">

    <xsl:for-each select="EvForm">

      <xsl:call-template name="EvFormRecord">
        
        <xsl:with-param name="RecordType">
          <xsl:text>Concomitant Medications:</xsl:text>
        </xsl:with-param>
      </xsl:call-template>
      
    </xsl:for-each>
  </xsl:template>
  <!--  

 ============================   Call TrialSubejctVisits Template   =========================
 
-->
  <!--
 -->
  <xsl:template match="EvCaseReportForm/Visits/EvMilestone">
    
    <xsl:call-template name="EvMilestones"></xsl:call-template>
    
  </xsl:template>
  <!--  

 ============================   Call AdverseEvents Template   =========================
 
-->

  <!--
 -->
  <xsl:template match="EvCaseReportForm/AdverseEvents">

    <xsl:for-each select="EvForm">

      <xsl:call-template name="EvFormRecord">
        <xsl:with-param name="RecordType">
          <xsl:text>Adverse Event Report:</xsl:text>
        </xsl:with-param>
      </xsl:call-template>

    </xsl:for-each>
  </xsl:template>

  <!--  

 ============================   Call AdverseEvents Template   =========================
-->

  <!--
  -->
  <xsl:template match="EvCaseReportForm/SeriousAdverseEvents">

    <xsl:for-each select="EvForm">

      <xsl:call-template name="EvFormRecord">
        <xsl:with-param name="RecordType">
          <xsl:text>Serious Adverse EventReports:</xsl:text>
        </xsl:with-param>
      </xsl:call-template>

    </xsl:for-each>

  </xsl:template>
  <!--
  
  <xsl:template match="text()"></xsl:template>
  -->

</xsl:stylesheet>
