<?xml version="1.0" encoding="ISO-8859-1" ?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"  >
  <!--
xmlns:fo="http://www.w3.org/1999/XSL/Format"


*******************************************************************************
*                COPYRIGHT (C) EVADO HOLDING PTY. LTD.  2002 - 2015
*
*                            ALL RIGHTS RESERVED
*
*******************************************************************************

-->
<!-- Includes 
  -->
<xsl:include href="./crf_d_el.xsl" />
<xsl:include href="./xFormHeader.xsl" />

  <xsl:variable name="textboxsize" select="10" />
  <xsl:variable name="ResponseColumn" select="33" />
  <xsl:output method="html" omit-xml-declaration="yes" indent="yes" encoding="ISO-8859-1" />
  <!--
  
    ====================== CLINICAL REPORT FORM - HeadER SECTION ================= 
     
  -->
  <xsl:template match="EvReport">
    <h1 align="Center" >Report</h1>
    <xsl:apply-templates />
    <p align="Center">
      Report generated by <xsl:value-of select="ReportCreatedBy" />on <xsl:value-of select="stReportCreated" />.
    </p>
    <br />



  </xsl:template>
  <!--  

 ============================   Call Trial Template   =========================
-->

  <xsl:template match="EvCaseReportForm/Trial">
    <xsl:call-template name="Trial"></xsl:call-template>
  </xsl:template>

  <!--  

 ============================   Call Subject Template   =========================
-->

  <xsl:template match="EvCaseReportForm/Subject">

    <p class="BlankSpace">.</p>
    <div class="Page_Break_Before">
    </div>
    <h2>Trial Subject:</h2>
    <xsl:call-template name="CrfFormFields">
      <xsl:with-param name="FormTypeId">
        <xsl:text>TS</xsl:text>
      </xsl:with-param>
    </xsl:call-template>
  </xsl:template>

  <!--  

 ============================   Call Medications Template   =========================
 
-->
  <xsl:template match="EvCaseReportForm/ConcomitantMedications">

    <xsl:for-each select="EvForm">
      <p class="BlankSpace">.</p>
      <div class="Page_Break_Before">
      </div>

      <xsl:choose>
        <xsl:when test ="position() = 1">
          <h2>Concomitant Medications:</h2>
        </xsl:when>
        <xsl:otherwise>
          <p class="BlankSpace">.</p>
        </xsl:otherwise>
      </xsl:choose>

      <xsl:choose>
        <xsl:when test ="string-length( RecordId ) > 0">
          <xsl:call-template name="FormHeader">
          </xsl:call-template>

          <xsl:call-template name="CrfFormFields">
            <xsl:with-param name="FormTypeId">
              <xsl:text>CM</xsl:text>
            </xsl:with-param>
          </xsl:call-template>
        </xsl:when>
        <xsl:otherwise>
          <h3 style="text-align:center;">No Records Collected</h3>
        </xsl:otherwise>
        </xsl:choose>
    </xsl:for-each>
  </xsl:template>

  <!--  

 ============================   Call TrialSubejctVisits Template   =========================
 
-->
  <xsl:template match="EvCaseReportForm/Visits/TrialSubjectVisit">
    <xsl:call-template name="TrialSubjectVisits"></xsl:call-template>
  </xsl:template>

  <!--  

 ============================   Call TrialSubjectTests Template   =========================
 
-->
 <xsl:template match="EvCaseReportForm/Tests/EvTest">
   <xsl:call-template name="TrialTests">
     </xsl:call-template>
   </xsl:template>

 <!--  

 ============================   Call AdverseEvents Template   =========================
 
-->
  <xsl:template match="EvCaseReportForm/AdverseEvents">

    <xsl:for-each select="EvForm">
      <p class="BlankSpace">.</p>
      <div class="Page_Break_Before">
      </div>

      <xsl:choose>
        <xsl:when test ="position() = 1">
          <h2>Adverse Events:</h2>
        </xsl:when>
        <xsl:otherwise>
          <p class="BlankSpace">.</p>
        </xsl:otherwise>
      </xsl:choose>

      <xsl:choose>
        <xsl:when test ="string-length( RecordId ) > 0">
          <xsl:call-template name="FormHeader">
          </xsl:call-template>

          <xsl:call-template name="CrfFormFields">
            <xsl:with-param name="FormTypeId">
              <xsl:text>AE</xsl:text>
            </xsl:with-param>
          </xsl:call-template>
        </xsl:when>
        <xsl:otherwise>
          <h3 style="text-align:center;">No Records Collected</h3>
        </xsl:otherwise>
        </xsl:choose>
    </xsl:for-each>
  </xsl:template>

  <!--  

 ============================   Call AdverseEvents Template   =========================
-->
  <xsl:template match="EvCaseReportForm/SeriousAdverseEvents">
    <xsl:for-each select="EvForm">
      <p class="BlankSpace">.</p>
      <div class="Page_Break_Before">
      </div>

      <xsl:choose>
        <xsl:when test ="position() = 1">
          <h2>Serious Adverse Events:</h2>
        </xsl:when>
        <xsl:otherwise>
          <p class="BlankSpace">.</p>
        </xsl:otherwise>
      </xsl:choose>

      <xsl:choose>
        <xsl:when test ="string-length( RecordId ) > 0">
          <xsl:call-template name="FormHeader">
          </xsl:call-template>

          <xsl:call-template name="CrfFormFields">
            <xsl:with-param name="FormTypeId">
              <xsl:text>SA</xsl:text>
            </xsl:with-param>
          </xsl:call-template>
        </xsl:when>
        <xsl:otherwise>
          <h3 style="text-align:center;">No Records Collected</h3>
        </xsl:otherwise>
      </xsl:choose>
    </xsl:for-each>
  </xsl:template>

  <!--  

 ============================   Call DoseLimitToxityReports Template   =========================

-->
  <xsl:template match="EvCaseReportForm/DoseLimitToxicities">
    <xsl:for-each select="EvForm">
      <p class="BlankSpace">.</p>
      <div class="Page_Break_Before">
      </div>

      <xsl:choose>
        <xsl:when test ="position() = 1">
          <h2>Dose Limit Toxicity Reports:</h2>
        </xsl:when>
        <xsl:otherwise>
          <p class="BlankSpace">.</p>
        </xsl:otherwise>
      </xsl:choose>

      <xsl:choose>
        <xsl:when test ="string-length( RecordId ) > 0">
          <xsl:call-template name="FormHeader">
          </xsl:call-template>

          <xsl:call-template name="CrfFormFields">
            <xsl:with-param name="FormTypeId">
              <xsl:text>DL</xsl:text>
            </xsl:with-param>
          </xsl:call-template>
        </xsl:when>
        <xsl:otherwise>
          <h3 style="text-align:center;">No Records Collected</h3>
        </xsl:otherwise>
        </xsl:choose>
    </xsl:for-each>
  </xsl:template>

  <!--
  
  <xsl:template match="text()"></xsl:template>
  -->

</xsl:stylesheet>
