//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evado.Model.Digital {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EvCustomerLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EvCustomerLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Evado.Model.Digital.EvCustomerLabels", typeof(EvCustomerLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Address:.
        /// </summary>
        public static string Customer_Address_Field_Label {
            get {
                return ResourceManager.GetString("Customer_Address_Field_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Administrator&apos;s name:.
        /// </summary>
        public static string Customer_Administator_Field_Label {
            get {
                return ResourceManager.GetString("Customer_Administator_Field_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Administrator&apos;s email address:.
        /// </summary>
        public static string Customer_AdministratorEmail_Field_Label {
            get {
                return ResourceManager.GetString("Customer_AdministratorEmail_Field_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADS Group Name:.
        /// </summary>
        public static string Customer_Ads_Group_Field_Label {
            get {
                return ResourceManager.GetString("Customer_Ads_Group_Field_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error raised when creating the customer..
        /// </summary>
        public static string Customer_Creation_Error_Message {
            get {
                return ResourceManager.GetString("Customer_Creation_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is current:.
        /// </summary>
        public static string Customer_Current_Field_Label {
            get {
                return ResourceManager.GetString("Customer_Current_Field_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Customer Settings.
        /// </summary>
        public static string Customer_Delete_Command_Title {
            get {
                return ResourceManager.GetString("Customer_Delete_Command_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Detsils.
        /// </summary>
        public static string Customer_Details_Group_Label {
            get {
                return ResourceManager.GetString("Customer_Details_Group_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer general email address:.
        /// </summary>
        public static string Customer_Email_Field_Label {
            get {
                return ResourceManager.GetString("Customer_Email_Field_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Unique identifier is empty..
        /// </summary>
        public static string Customer_Guid_Empty_Message {
            get {
                return ResourceManager.GetString("Customer_Guid_Empty_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page Header content:.
        /// </summary>
        public static string Customer_Home_Page_Header_Field_Label {
            get {
                return ResourceManager.GetString("Customer_Home_Page_Header_Field_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Single Study enviornment:.
        /// </summary>
        public static string Customer_IsSingleStudy_Field_Label {
            get {
                return ResourceManager.GetString("Customer_IsSingleStudy_Field_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error raised generating the customer list..
        /// </summary>
        public static string Customer_List_Error_Message {
            get {
                return ResourceManager.GetString("Customer_List_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer List.
        /// </summary>
        public static string Customer_List_Group_Title {
            get {
                return ResourceManager.GetString("Customer_List_Group_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evado Clinical Customer List.
        /// </summary>
        public static string Customer_List_Page_Title {
            get {
                return ResourceManager.GetString("Customer_List_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name has not be provided.
        /// </summary>
        public static string Customer_Name_Error_Message {
            get {
                return ResourceManager.GetString("Customer_Name_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name:.
        /// </summary>
        public static string Customer_Name_Field_Label {
            get {
                return ResourceManager.GetString("Customer_Name_Field_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Customer.
        /// </summary>
        public static string Customer_New_Command_Title {
            get {
                return ResourceManager.GetString("Customer_New_Command_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer No:.
        /// </summary>
        public static string Customer_No_Field_Label {
            get {
                return ResourceManager.GetString("Customer_No_Field_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        public static string Customer_No_Name_Format {
            get {
                return ResourceManager.GetString("Customer_No_Name_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Studies:.
        /// </summary>
        public static string Customer_No_of_Studies_Field_Label {
            get {
                return ResourceManager.GetString("Customer_No_of_Studies_Field_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error raised generating the customer properties page..
        /// </summary>
        public static string Customer_Page_Error_Message {
            get {
                return ResourceManager.GetString("Customer_Page_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Settings.
        /// </summary>
        public static string Customer_Page_Title {
            get {
                return ResourceManager.GetString("Customer_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Customer Settings.
        /// </summary>
        public static string Customer_Save_Command_Title {
            get {
                return ResourceManager.GetString("Customer_Save_Command_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Service Type:.
        /// </summary>
        public static string Customer_Service_Field_Label {
            get {
                return ResourceManager.GetString("Customer_Service_Field_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Settings.
        /// </summary>
        public static string Customer_Settings_Group_Label {
            get {
                return ResourceManager.GetString("Customer_Settings_Group_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Status: .
        /// </summary>
        public static string Customer_State_Field_Label {
            get {
                return ResourceManager.GetString("Customer_State_Field_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer main telephone:.
        /// </summary>
        public static string Customer_Telephone_Field_Label {
            get {
                return ResourceManager.GetString("Customer_Telephone_Field_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error raised updating the customer settings..
        /// </summary>
        public static string Customer_Update_Error_Message {
            get {
                return ResourceManager.GetString("Customer_Update_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Customer is {0} - {1}..
        /// </summary>
        public static string Customer_User_Name_Format {
            get {
                return ResourceManager.GetString("Customer_User_Name_Format", resourceCulture);
            }
        }
    }
}
